/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class AccessoryBuilder {
    //the instance to build
    private Accessory accessory;

    /**
     * Default constructor to initialize the instance
     */
    public AccessoryBuilder() {
        accessory = new Accessory();
    }

    public AccessoryBuilder aSIN(String aSIN) {
        accessory.setASIN(aSIN);
        return this;
    }

    public AccessoryBuilder title(String title) {
        accessory.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Accessory build() {
        return accessory;
    }
}