/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class AlternateVersionBuilder {
    //the instance to build
    private AlternateVersion alternateVersion;

    /**
     * Default constructor to initialize the instance
     */
    public AlternateVersionBuilder() {
        alternateVersion = new AlternateVersion();
    }

    public AlternateVersionBuilder aSIN(String aSIN) {
        alternateVersion.setASIN(aSIN);
        return this;
    }

    public AlternateVersionBuilder title(String title) {
        alternateVersion.setTitle(title);
        return this;
    }

    public AlternateVersionBuilder binding(String binding) {
        alternateVersion.setBinding(binding);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AlternateVersion build() {
        return alternateVersion;
    }
}