/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class AlternateVersionsBuilder {
    //the instance to build
    private AlternateVersions alternateVersions;

    /**
     * Default constructor to initialize the instance
     */
    public AlternateVersionsBuilder() {
        alternateVersions = new AlternateVersions();
    }

    public AlternateVersionsBuilder alternateVersion(List<AlternateVersion> alternateVersion) {
        alternateVersions.setAlternateVersion(alternateVersion);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AlternateVersions build() {
        return alternateVersions;
    }
}