/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AlternateVersions 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5001987204643088962L;
    private List<AlternateVersion> alternateVersion;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("AlternateVersion")
    public List<AlternateVersion> getAlternateVersion ( ) { 
        return this.alternateVersion;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("AlternateVersion")
    public void setAlternateVersion (List<AlternateVersion> value) { 
        this.alternateVersion = value;
    }
 
}
 