/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class AncestorsBuilder {
    //the instance to build
    private Ancestors ancestors;

    /**
     * Default constructor to initialize the instance
     */
    public AncestorsBuilder() {
        ancestors = new Ancestors();
    }

    public AncestorsBuilder browseNode(List<BrowseNode> browseNode) {
        ancestors.setBrowseNode(browseNode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Ancestors build() {
        return ancestors;
    }
}