/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Arguments 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5554873120034664791L;
    private List<Argument> argument;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Argument")
    public List<Argument> getArgument ( ) { 
        return this.argument;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Argument")
    public void setArgument (List<Argument> value) { 
        this.argument = value;
    }
 
}
 