/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ArgumentsBuilder {
    //the instance to build
    private Arguments arguments;

    /**
     * Default constructor to initialize the instance
     */
    public ArgumentsBuilder() {
        arguments = new Arguments();
    }

    public ArgumentsBuilder argument(List<Argument> argument) {
        arguments.setArgument(argument);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Arguments build() {
        return arguments;
    }
}