/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ArgumentBuilder {
    //the instance to build
    private Argument argument;

    /**
     * Default constructor to initialize the instance
     */
    public ArgumentBuilder() {
        argument = new Argument();
    }

    public ArgumentBuilder name(String name) {
        argument.setName(name);
        return this;
    }

    public ArgumentBuilder value(String value) {
        argument.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Argument build() {
        return argument;
    }
}