/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum AudienceRatingEnum {
    G, //TODO: Write general description for this element
    PG, //TODO: Write general description for this element
    PG13, //TODO: Write general description for this element
    R, //TODO: Write general description for this element
    NC17, //TODO: Write general description for this element
    NR, //TODO: Write general description for this element
    UNRATED, //TODO: Write general description for this element
    ENUM_6, //TODO: Write general description for this element
    ENUM_12, //TODO: Write general description for this element
    ENUM_16, //TODO: Write general description for this element
    ENUM_18, //TODO: Write general description for this element
    FAMILYVIEWING; //TODO: Write general description for this element

    private static TreeMap<String, AudienceRatingEnum> valueMap = new TreeMap<String, AudienceRatingEnum>();
    private String value;

    static {
        G.value = "G";
        PG.value = "PG";
        PG13.value = "PG-13";
        R.value = "R";
        NC17.value = "NC-17";
        NR.value = "NR";
        UNRATED.value = "Unrated";
        ENUM_6.value = "6";
        ENUM_12.value = "12";
        ENUM_16.value = "16";
        ENUM_18.value = "18";
        FAMILYVIEWING.value = "FamilyViewing";

        valueMap.put("G", G);
        valueMap.put("PG", PG);
        valueMap.put("PG-13", PG13);
        valueMap.put("R", R);
        valueMap.put("NC-17", NC17);
        valueMap.put("NR", NR);
        valueMap.put("Unrated", UNRATED);
        valueMap.put("6", ENUM_6);
        valueMap.put("12", ENUM_12);
        valueMap.put("16", ENUM_16);
        valueMap.put("18", ENUM_18);
        valueMap.put("FamilyViewing", FAMILYVIEWING);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static AudienceRatingEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AudienceRatingEnum values to list of string values
     * @param toConvert The list of AudienceRatingEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<AudienceRatingEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (AudienceRatingEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 