/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum AvailabilityEnum {
    AVAILABLE; //TODO: Write general description for this element

    private static TreeMap<String, AvailabilityEnum> valueMap = new TreeMap<String, AvailabilityEnum>();
    private String value;

    static {
        AVAILABLE.value = "Available";

        valueMap.put("Available", AVAILABLE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static AvailabilityEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AvailabilityEnum values to list of string values
     * @param toConvert The list of AvailabilityEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<AvailabilityEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (AvailabilityEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 