/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class AvailabilityAttributesBuilder {
    //the instance to build
    private AvailabilityAttributes availabilityAttributes;

    /**
     * Default constructor to initialize the instance
     */
    public AvailabilityAttributesBuilder() {
        availabilityAttributes = new AvailabilityAttributes();
    }

    public AvailabilityAttributesBuilder availabilityType(String availabilityType) {
        availabilityAttributes.setAvailabilityType(availabilityType);
        return this;
    }

    public AvailabilityAttributesBuilder isPreorder(Boolean isPreorder) {
        availabilityAttributes.setIsPreorder(isPreorder);
        return this;
    }

    public AvailabilityAttributesBuilder minimumHours(Integer minimumHours) {
        availabilityAttributes.setMinimumHours(minimumHours);
        return this;
    }

    public AvailabilityAttributesBuilder maximumHours(Integer maximumHours) {
        availabilityAttributes.setMaximumHours(maximumHours);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AvailabilityAttributes build() {
        return availabilityAttributes;
    }
}