/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class BinParameterBuilder {
    //the instance to build
    private BinParameter binParameter;

    /**
     * Default constructor to initialize the instance
     */
    public BinParameterBuilder() {
        binParameter = new BinParameter();
    }

    public BinParameterBuilder name(String name) {
        binParameter.setName(name);
        return this;
    }

    public BinParameterBuilder value(String value) {
        binParameter.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BinParameter build() {
        return binParameter;
    }
}