/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class BrowseNodeLookupResponseMsgBuilder {
    //the instance to build
    private BrowseNodeLookupResponseMsg browseNodeLookupResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public BrowseNodeLookupResponseMsgBuilder() {
        browseNodeLookupResponseMsg = new BrowseNodeLookupResponseMsg();
    }

    public BrowseNodeLookupResponseMsgBuilder body(BrowseNodeLookupResponse body) {
        browseNodeLookupResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BrowseNodeLookupResponseMsg build() {
        return browseNodeLookupResponseMsg;
    }
}