/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class BrowseNodeLookupRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5188042825861762134L;
    private List<String> browseNodeId;
    private List<String> responseGroup;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("BrowseNodeId")
    public List<String> getBrowseNodeId ( ) { 
        return this.browseNodeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("BrowseNodeId")
    public void setBrowseNodeId (List<String> value) { 
        this.browseNodeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ResponseGroup")
    public List<String> getResponseGroup ( ) { 
        return this.responseGroup;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ResponseGroup")
    public void setResponseGroup (List<String> value) { 
        this.responseGroup = value;
    }
 
}
 