/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class BrowseNodeLookupBuilder {
    //the instance to build
    private BrowseNodeLookup browseNodeLookup;

    /**
     * Default constructor to initialize the instance
     */
    public BrowseNodeLookupBuilder() {
        browseNodeLookup = new BrowseNodeLookup();
    }

    public BrowseNodeLookupBuilder marketplaceDomain(String marketplaceDomain) {
        browseNodeLookup.setMarketplaceDomain(marketplaceDomain);
        return this;
    }

    public BrowseNodeLookupBuilder aWSAccessKeyId(String aWSAccessKeyId) {
        browseNodeLookup.setAWSAccessKeyId(aWSAccessKeyId);
        return this;
    }

    public BrowseNodeLookupBuilder associateTag(String associateTag) {
        browseNodeLookup.setAssociateTag(associateTag);
        return this;
    }

    public BrowseNodeLookupBuilder validate(String validate) {
        browseNodeLookup.setValidate(validate);
        return this;
    }

    public BrowseNodeLookupBuilder xMLEscaping(String xMLEscaping) {
        browseNodeLookup.setXMLEscaping(xMLEscaping);
        return this;
    }

    public BrowseNodeLookupBuilder shared(BrowseNodeLookupRequest shared) {
        browseNodeLookup.setShared(shared);
        return this;
    }

    public BrowseNodeLookupBuilder request(List<BrowseNodeLookupRequest> request) {
        browseNodeLookup.setRequest(request);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BrowseNodeLookup build() {
        return browseNodeLookup;
    }
}