/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class BrowseNodeLookupRequestBuilder {
    //the instance to build
    private BrowseNodeLookupRequest browseNodeLookupRequest;

    /**
     * Default constructor to initialize the instance
     */
    public BrowseNodeLookupRequestBuilder() {
        browseNodeLookupRequest = new BrowseNodeLookupRequest();
    }

    public BrowseNodeLookupRequestBuilder browseNodeId(List<String> browseNodeId) {
        browseNodeLookupRequest.setBrowseNodeId(browseNodeId);
        return this;
    }

    public BrowseNodeLookupRequestBuilder responseGroup(List<String> responseGroup) {
        browseNodeLookupRequest.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BrowseNodeLookupRequest build() {
        return browseNodeLookupRequest;
    }
}