/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartModifyRequestBuilder {
    //the instance to build
    private CartModifyRequest cartModifyRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CartModifyRequestBuilder() {
        cartModifyRequest = new CartModifyRequest();
    }

    public CartModifyRequestBuilder cartId(String cartId) {
        cartModifyRequest.setCartId(cartId);
        return this;
    }

    public CartModifyRequestBuilder hMAC(String hMAC) {
        cartModifyRequest.setHMAC(hMAC);
        return this;
    }

    public CartModifyRequestBuilder mergeCart(String mergeCart) {
        cartModifyRequest.setMergeCart(mergeCart);
        return this;
    }

    public CartModifyRequestBuilder items(Items35 items) {
        cartModifyRequest.setItems(items);
        return this;
    }

    public CartModifyRequestBuilder responseGroup(List<String> responseGroup) {
        cartModifyRequest.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartModifyRequest build() {
        return cartModifyRequest;
    }
}