/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartCreateRequestBuilder {
    //the instance to build
    private CartCreateRequest cartCreateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CartCreateRequestBuilder() {
        cartCreateRequest = new CartCreateRequest();
    }

    public CartCreateRequestBuilder mergeCart(String mergeCart) {
        cartCreateRequest.setMergeCart(mergeCart);
        return this;
    }

    public CartCreateRequestBuilder items(Items24 items) {
        cartCreateRequest.setItems(items);
        return this;
    }

    public CartCreateRequestBuilder responseGroup(List<String> responseGroup) {
        cartCreateRequest.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartCreateRequest build() {
        return cartCreateRequest;
    }
}