/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartClearRequestBuilder {
    //the instance to build
    private CartClearRequest cartClearRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CartClearRequestBuilder() {
        cartClearRequest = new CartClearRequest();
    }

    public CartClearRequestBuilder cartId(String cartId) {
        cartClearRequest.setCartId(cartId);
        return this;
    }

    public CartClearRequestBuilder hMAC(String hMAC) {
        cartClearRequest.setHMAC(hMAC);
        return this;
    }

    public CartClearRequestBuilder mergeCart(String mergeCart) {
        cartClearRequest.setMergeCart(mergeCart);
        return this;
    }

    public CartClearRequestBuilder responseGroup(List<String> responseGroup) {
        cartClearRequest.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartClearRequest build() {
        return cartClearRequest;
    }
}