/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartItemsBuilder {
    //the instance to build
    private CartItems cartItems;

    /**
     * Default constructor to initialize the instance
     */
    public CartItemsBuilder() {
        cartItems = new CartItems();
    }

    public CartItemsBuilder cartItem(List<CartItem> cartItem) {
        cartItems.setCartItem(cartItem);
        return this;
    }

    public CartItemsBuilder subTotal(Price subTotal) {
        cartItems.setSubTotal(subTotal);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartItems build() {
        return cartItems;
    }
}