/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartCreateResponseBuilder {
    //the instance to build
    private CartCreateResponse cartCreateResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CartCreateResponseBuilder() {
        cartCreateResponse = new CartCreateResponse();
    }

    public CartCreateResponseBuilder operationRequest(OperationRequest operationRequest) {
        cartCreateResponse.setOperationRequest(operationRequest);
        return this;
    }

    public CartCreateResponseBuilder cart(List<Cart> cart) {
        cartCreateResponse.setCart(cart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartCreateResponse build() {
        return cartCreateResponse;
    }
}