/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartCreateRequest55Builder {
    //the instance to build
    private CartCreateRequest55 cartCreateRequest55;

    /**
     * Default constructor to initialize the instance
     */
    public CartCreateRequest55Builder() {
        cartCreateRequest55 = new CartCreateRequest55();
    }

    public CartCreateRequest55Builder mergeCart(String mergeCart) {
        cartCreateRequest55.setMergeCart(mergeCart);
        return this;
    }

    public CartCreateRequest55Builder items(Items items) {
        cartCreateRequest55.setItems(items);
        return this;
    }

    public CartCreateRequest55Builder responseGroup(List<String> responseGroup) {
        cartCreateRequest55.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartCreateRequest55 build() {
        return cartCreateRequest55;
    }
}