/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartAddResponseMsgBuilder {
    //the instance to build
    private CartAddResponseMsg cartAddResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartAddResponseMsgBuilder() {
        cartAddResponseMsg = new CartAddResponseMsg();
    }

    public CartAddResponseMsgBuilder body(CartAddResponse body) {
        cartAddResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartAddResponseMsg build() {
        return cartAddResponseMsg;
    }
}