/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartModifyResponseBuilder {
    //the instance to build
    private CartModifyResponse cartModifyResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CartModifyResponseBuilder() {
        cartModifyResponse = new CartModifyResponse();
    }

    public CartModifyResponseBuilder operationRequest(OperationRequest operationRequest) {
        cartModifyResponse.setOperationRequest(operationRequest);
        return this;
    }

    public CartModifyResponseBuilder cart(List<Cart> cart) {
        cartModifyResponse.setCart(cart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartModifyResponse build() {
        return cartModifyResponse;
    }
}