/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartGetResponseBuilder {
    //the instance to build
    private CartGetResponse cartGetResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CartGetResponseBuilder() {
        cartGetResponse = new CartGetResponse();
    }

    public CartGetResponseBuilder operationRequest(OperationRequest operationRequest) {
        cartGetResponse.setOperationRequest(operationRequest);
        return this;
    }

    public CartGetResponseBuilder cart(List<Cart> cart) {
        cartGetResponse.setCart(cart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartGetResponse build() {
        return cartGetResponse;
    }
}