/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartCreateBuilder {
    //the instance to build
    private CartCreate cartCreate;

    /**
     * Default constructor to initialize the instance
     */
    public CartCreateBuilder() {
        cartCreate = new CartCreate();
    }

    public CartCreateBuilder marketplaceDomain(String marketplaceDomain) {
        cartCreate.setMarketplaceDomain(marketplaceDomain);
        return this;
    }

    public CartCreateBuilder aWSAccessKeyId(String aWSAccessKeyId) {
        cartCreate.setAWSAccessKeyId(aWSAccessKeyId);
        return this;
    }

    public CartCreateBuilder associateTag(String associateTag) {
        cartCreate.setAssociateTag(associateTag);
        return this;
    }

    public CartCreateBuilder validate(String validate) {
        cartCreate.setValidate(validate);
        return this;
    }

    public CartCreateBuilder xMLEscaping(String xMLEscaping) {
        cartCreate.setXMLEscaping(xMLEscaping);
        return this;
    }

    public CartCreateBuilder shared(CartCreateRequest shared) {
        cartCreate.setShared(shared);
        return this;
    }

    public CartCreateBuilder request(List<CartCreateRequest> request) {
        cartCreate.setRequest(request);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartCreate build() {
        return cartCreate;
    }
}