/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartModifyRequestMsgBuilder {
    //the instance to build
    private CartModifyRequestMsg cartModifyRequestMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartModifyRequestMsgBuilder() {
        cartModifyRequestMsg = new CartModifyRequestMsg();
    }

    public CartModifyRequestMsgBuilder body(CartModify body) {
        cartModifyRequestMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartModifyRequestMsg build() {
        return cartModifyRequestMsg;
    }
}