/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartClearResponseMsgBuilder {
    //the instance to build
    private CartClearResponseMsg cartClearResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartClearResponseMsgBuilder() {
        cartClearResponseMsg = new CartClearResponseMsg();
    }

    public CartClearResponseMsgBuilder body(CartClearResponse body) {
        cartClearResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartClearResponseMsg build() {
        return cartClearResponseMsg;
    }
}