/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartClearResponseBuilder {
    //the instance to build
    private CartClearResponse cartClearResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CartClearResponseBuilder() {
        cartClearResponse = new CartClearResponse();
    }

    public CartClearResponseBuilder operationRequest(OperationRequest operationRequest) {
        cartClearResponse.setOperationRequest(operationRequest);
        return this;
    }

    public CartClearResponseBuilder cart(List<Cart> cart) {
        cartClearResponse.setCart(cart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartClearResponse build() {
        return cartClearResponse;
    }
}