/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartModifyResponseMsgBuilder {
    //the instance to build
    private CartModifyResponseMsg cartModifyResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartModifyResponseMsgBuilder() {
        cartModifyResponseMsg = new CartModifyResponseMsg();
    }

    public CartModifyResponseMsgBuilder body(CartModifyResponse body) {
        cartModifyResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartModifyResponseMsg build() {
        return cartModifyResponseMsg;
    }
}