/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartCreateRequestMsgBuilder {
    //the instance to build
    private CartCreateRequestMsg cartCreateRequestMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartCreateRequestMsgBuilder() {
        cartCreateRequestMsg = new CartCreateRequestMsg();
    }

    public CartCreateRequestMsgBuilder body(CartCreate body) {
        cartCreateRequestMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartCreateRequestMsg build() {
        return cartCreateRequestMsg;
    }
}