/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartAddRequestMsgBuilder {
    //the instance to build
    private CartAddRequestMsg cartAddRequestMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartAddRequestMsgBuilder() {
        cartAddRequestMsg = new CartAddRequestMsg();
    }

    public CartAddRequestMsgBuilder body(CartAdd body) {
        cartAddRequestMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartAddRequestMsg build() {
        return cartAddRequestMsg;
    }
}