/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartGetRequestMsgBuilder {
    //the instance to build
    private CartGetRequestMsg cartGetRequestMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartGetRequestMsgBuilder() {
        cartGetRequestMsg = new CartGetRequestMsg();
    }

    public CartGetRequestMsgBuilder body(CartGet body) {
        cartGetRequestMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartGetRequestMsg build() {
        return cartGetRequestMsg;
    }
}