/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartAddResponseBuilder {
    //the instance to build
    private CartAddResponse cartAddResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CartAddResponseBuilder() {
        cartAddResponse = new CartAddResponse();
    }

    public CartAddResponseBuilder operationRequest(OperationRequest operationRequest) {
        cartAddResponse.setOperationRequest(operationRequest);
        return this;
    }

    public CartAddResponseBuilder cart(List<Cart> cart) {
        cartAddResponse.setCart(cart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartAddResponse build() {
        return cartAddResponse;
    }
}