/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartGetBuilder {
    //the instance to build
    private CartGet cartGet;

    /**
     * Default constructor to initialize the instance
     */
    public CartGetBuilder() {
        cartGet = new CartGet();
    }

    public CartGetBuilder marketplaceDomain(String marketplaceDomain) {
        cartGet.setMarketplaceDomain(marketplaceDomain);
        return this;
    }

    public CartGetBuilder aWSAccessKeyId(String aWSAccessKeyId) {
        cartGet.setAWSAccessKeyId(aWSAccessKeyId);
        return this;
    }

    public CartGetBuilder associateTag(String associateTag) {
        cartGet.setAssociateTag(associateTag);
        return this;
    }

    public CartGetBuilder validate(String validate) {
        cartGet.setValidate(validate);
        return this;
    }

    public CartGetBuilder xMLEscaping(String xMLEscaping) {
        cartGet.setXMLEscaping(xMLEscaping);
        return this;
    }

    public CartGetBuilder shared(CartGetRequest shared) {
        cartGet.setShared(shared);
        return this;
    }

    public CartGetBuilder request(List<CartGetRequest> request) {
        cartGet.setRequest(request);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartGet build() {
        return cartGet;
    }
}