/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartGetResponseMsgBuilder {
    //the instance to build
    private CartGetResponseMsg cartGetResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartGetResponseMsgBuilder() {
        cartGetResponseMsg = new CartGetResponseMsg();
    }

    public CartGetResponseMsgBuilder body(CartGetResponse body) {
        cartGetResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartGetResponseMsg build() {
        return cartGetResponseMsg;
    }
}