/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartAddRequestBuilder {
    //the instance to build
    private CartAddRequest cartAddRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CartAddRequestBuilder() {
        cartAddRequest = new CartAddRequest();
    }

    public CartAddRequestBuilder cartId(String cartId) {
        cartAddRequest.setCartId(cartId);
        return this;
    }

    public CartAddRequestBuilder hMAC(String hMAC) {
        cartAddRequest.setHMAC(hMAC);
        return this;
    }

    public CartAddRequestBuilder mergeCart(String mergeCart) {
        cartAddRequest.setMergeCart(mergeCart);
        return this;
    }

    public CartAddRequestBuilder items(Items items) {
        cartAddRequest.setItems(items);
        return this;
    }

    public CartAddRequestBuilder responseGroup(List<String> responseGroup) {
        cartAddRequest.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartAddRequest build() {
        return cartAddRequest;
    }
}