/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartBuilder {
    //the instance to build
    private Cart cart;

    /**
     * Default constructor to initialize the instance
     */
    public CartBuilder() {
        cart = new Cart();
    }

    public CartBuilder cartId(String cartId) {
        cart.setCartId(cartId);
        return this;
    }

    public CartBuilder hMAC(String hMAC) {
        cart.setHMAC(hMAC);
        return this;
    }

    public CartBuilder uRLEncodedHMAC(String uRLEncodedHMAC) {
        cart.setURLEncodedHMAC(uRLEncodedHMAC);
        return this;
    }

    public CartBuilder request(Request162 request) {
        cart.setRequest(request);
        return this;
    }

    public CartBuilder purchaseURL(String purchaseURL) {
        cart.setPurchaseURL(purchaseURL);
        return this;
    }

    public CartBuilder mobileCartURL(String mobileCartURL) {
        cart.setMobileCartURL(mobileCartURL);
        return this;
    }

    public CartBuilder subTotal(Price subTotal) {
        cart.setSubTotal(subTotal);
        return this;
    }

    public CartBuilder cartItems(CartItems cartItems) {
        cart.setCartItems(cartItems);
        return this;
    }

    public CartBuilder savedForLaterItems(SavedForLaterItems savedForLaterItems) {
        cart.setSavedForLaterItems(savedForLaterItems);
        return this;
    }

    public CartBuilder similarProducts(SimilarProducts similarProducts) {
        cart.setSimilarProducts(similarProducts);
        return this;
    }

    public CartBuilder topSellers(TopSellers topSellers) {
        cart.setTopSellers(topSellers);
        return this;
    }

    public CartBuilder newReleases(NewReleases newReleases) {
        cart.setNewReleases(newReleases);
        return this;
    }

    public CartBuilder similarViewedProducts(SimilarViewedProducts similarViewedProducts) {
        cart.setSimilarViewedProducts(similarViewedProducts);
        return this;
    }

    public CartBuilder otherCategoriesSimilarProducts(OtherCategoriesSimilarProducts otherCategoriesSimilarProducts) {
        cart.setOtherCategoriesSimilarProducts(otherCategoriesSimilarProducts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Cart build() {
        return cart;
    }
}