/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartGetRequestBuilder {
    //the instance to build
    private CartGetRequest cartGetRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CartGetRequestBuilder() {
        cartGetRequest = new CartGetRequest();
    }

    public CartGetRequestBuilder cartId(String cartId) {
        cartGetRequest.setCartId(cartId);
        return this;
    }

    public CartGetRequestBuilder hMAC(String hMAC) {
        cartGetRequest.setHMAC(hMAC);
        return this;
    }

    public CartGetRequestBuilder mergeCart(String mergeCart) {
        cartGetRequest.setMergeCart(mergeCart);
        return this;
    }

    public CartGetRequestBuilder responseGroup(List<String> responseGroup) {
        cartGetRequest.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartGetRequest build() {
        return cartGetRequest;
    }
}