/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartModifyRequest56Builder {
    //the instance to build
    private CartModifyRequest56 cartModifyRequest56;

    /**
     * Default constructor to initialize the instance
     */
    public CartModifyRequest56Builder() {
        cartModifyRequest56 = new CartModifyRequest56();
    }

    public CartModifyRequest56Builder cartId(String cartId) {
        cartModifyRequest56.setCartId(cartId);
        return this;
    }

    public CartModifyRequest56Builder hMAC(String hMAC) {
        cartModifyRequest56.setHMAC(hMAC);
        return this;
    }

    public CartModifyRequest56Builder mergeCart(String mergeCart) {
        cartModifyRequest56.setMergeCart(mergeCart);
        return this;
    }

    public CartModifyRequest56Builder items(Items items) {
        cartModifyRequest56.setItems(items);
        return this;
    }

    public CartModifyRequest56Builder responseGroup(List<String> responseGroup) {
        cartModifyRequest56.setResponseGroup(responseGroup);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartModifyRequest56 build() {
        return cartModifyRequest56;
    }
}