/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CartCreateResponseMsgBuilder {
    //the instance to build
    private CartCreateResponseMsg cartCreateResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public CartCreateResponseMsgBuilder() {
        cartCreateResponseMsg = new CartCreateResponseMsg();
    }

    public CartCreateResponseMsgBuilder body(CartCreateResponse body) {
        cartCreateResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartCreateResponseMsg build() {
        return cartCreateResponseMsg;
    }
}