/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ChildrenBuilder {
    //the instance to build
    private Children children;

    /**
     * Default constructor to initialize the instance
     */
    public ChildrenBuilder() {
        children = new Children();
    }

    public ChildrenBuilder browseNode(List<BrowseNode> browseNode) {
        children.setBrowseNode(browseNode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Children build() {
        return children;
    }
}