/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CollectionSummaryBuilder {
    //the instance to build
    private CollectionSummary collectionSummary;

    /**
     * Default constructor to initialize the instance
     */
    public CollectionSummaryBuilder() {
        collectionSummary = new CollectionSummary();
    }

    public CollectionSummaryBuilder lowestListPrice(Price lowestListPrice) {
        collectionSummary.setLowestListPrice(lowestListPrice);
        return this;
    }

    public CollectionSummaryBuilder highestListPrice(Price highestListPrice) {
        collectionSummary.setHighestListPrice(highestListPrice);
        return this;
    }

    public CollectionSummaryBuilder lowestSalePrice(Price lowestSalePrice) {
        collectionSummary.setLowestSalePrice(lowestSalePrice);
        return this;
    }

    public CollectionSummaryBuilder highestSalePrice(Price highestSalePrice) {
        collectionSummary.setHighestSalePrice(highestSalePrice);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CollectionSummary build() {
        return collectionSummary;
    }
}