/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CollectionSummary 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4926067015957361722L;
    private Price lowestListPrice;
    private Price highestListPrice;
    private Price lowestSalePrice;
    private Price highestSalePrice;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("LowestListPrice")
    public Price getLowestListPrice ( ) { 
        return this.lowestListPrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("LowestListPrice")
    public void setLowestListPrice (Price value) { 
        this.lowestListPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("HighestListPrice")
    public Price getHighestListPrice ( ) { 
        return this.highestListPrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("HighestListPrice")
    public void setHighestListPrice (Price value) { 
        this.highestListPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("LowestSalePrice")
    public Price getLowestSalePrice ( ) { 
        return this.lowestSalePrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("LowestSalePrice")
    public void setLowestSalePrice (Price value) { 
        this.lowestSalePrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("HighestSalePrice")
    public Price getHighestSalePrice ( ) { 
        return this.highestSalePrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("HighestSalePrice")
    public void setHighestSalePrice (Price value) { 
        this.highestSalePrice = value;
    }
 
}
 