/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CollectionItemBuilder {
    //the instance to build
    private CollectionItem collectionItem;

    /**
     * Default constructor to initialize the instance
     */
    public CollectionItemBuilder() {
        collectionItem = new CollectionItem();
    }

    public CollectionItemBuilder aSIN(String aSIN) {
        collectionItem.setASIN(aSIN);
        return this;
    }

    public CollectionItemBuilder title(String title) {
        collectionItem.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CollectionItem build() {
        return collectionItem;
    }
}