/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Collections 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4711550691258296246L;
    private List<MCollection> collection;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Collection")
    public List<MCollection> getMCollection ( ) { 
        return this.collection;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Collection")
    public void setMCollection (List<MCollection> value) { 
        this.collection = value;
    }
 
}
 