/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CollectionParentBuilder {
    //the instance to build
    private CollectionParent collectionParent;

    /**
     * Default constructor to initialize the instance
     */
    public CollectionParentBuilder() {
        collectionParent = new CollectionParent();
    }

    public CollectionParentBuilder aSIN(String aSIN) {
        collectionParent.setASIN(aSIN);
        return this;
    }

    public CollectionParentBuilder title(String title) {
        collectionParent.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CollectionParent build() {
        return collectionParent;
    }
}