/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ConditionEnum {
    ALL, //TODO: Write general description for this element
    NEW, //TODO: Write general description for this element
    USED, //TODO: Write general description for this element
    COLLECTIBLE, //TODO: Write general description for this element
    REFURBISHED; //TODO: Write general description for this element

    private static TreeMap<String, ConditionEnum> valueMap = new TreeMap<String, ConditionEnum>();
    private String value;

    static {
        ALL.value = "All";
        NEW.value = "New";
        USED.value = "Used";
        COLLECTIBLE.value = "Collectible";
        REFURBISHED.value = "Refurbished";

        valueMap.put("All", ALL);
        valueMap.put("New", NEW);
        valueMap.put("Used", USED);
        valueMap.put("Collectible", COLLECTIBLE);
        valueMap.put("Refurbished", REFURBISHED);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ConditionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ConditionEnum values to list of string values
     * @param toConvert The list of ConditionEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ConditionEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ConditionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 