/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CorrectedQueryBuilder {
    //the instance to build
    private CorrectedQuery correctedQuery;

    /**
     * Default constructor to initialize the instance
     */
    public CorrectedQueryBuilder() {
        correctedQuery = new CorrectedQuery();
    }

    public CorrectedQueryBuilder keywords(String keywords) {
        correctedQuery.setKeywords(keywords);
        return this;
    }

    public CorrectedQueryBuilder message(String message) {
        correctedQuery.setMessage(message);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CorrectedQuery build() {
        return correctedQuery;
    }
}