/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CreatorBuilder {
    //the instance to build
    private Creator creator;

    /**
     * Default constructor to initialize the instance
     */
    public CreatorBuilder() {
        creator = new Creator();
    }

    public CreatorBuilder role(String role) {
        creator.setRole(role);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Creator build() {
        return creator;
    }
}