/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class CustomerReviewsBuilder {
    //the instance to build
    private CustomerReviews customerReviews;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerReviewsBuilder() {
        customerReviews = new CustomerReviews();
    }

    public CustomerReviewsBuilder iFrameURL(String iFrameURL) {
        customerReviews.setIFrameURL(iFrameURL);
        return this;
    }

    public CustomerReviewsBuilder hasReviews(Boolean hasReviews) {
        customerReviews.setHasReviews(hasReviews);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerReviews build() {
        return customerReviews;
    }
}