/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class DecimalWithUnitsBuilder {
    //the instance to build
    private DecimalWithUnits decimalWithUnits;

    /**
     * Default constructor to initialize the instance
     */
    public DecimalWithUnitsBuilder() {
        decimalWithUnits = new DecimalWithUnits();
    }

    public DecimalWithUnitsBuilder units(String units) {
        decimalWithUnits.setUnits(units);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DecimalWithUnits build() {
        return decimalWithUnits;
    }
}