/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DecimalWithUnits 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5349532609367424995L;
    private String units;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Units")
    public String getUnits ( ) { 
        return this.units;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Units")
    public void setUnits (String value) { 
        this.units = value;
    }
 
}
 