/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class EANListBuilder {
    //the instance to build
    private EANList eANList;

    /**
     * Default constructor to initialize the instance
     */
    public EANListBuilder() {
        eANList = new EANList();
    }

    public EANListBuilder eANListElement(List<String> eANListElement) {
        eANList.setEANListElement(eANListElement);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EANList build() {
        return eANList;
    }
}