/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class EditorialReviewBuilder {
    //the instance to build
    private EditorialReview editorialReview;

    /**
     * Default constructor to initialize the instance
     */
    public EditorialReviewBuilder() {
        editorialReview = new EditorialReview();
    }

    public EditorialReviewBuilder source(String source) {
        editorialReview.setSource(source);
        return this;
    }

    public EditorialReviewBuilder content(String content) {
        editorialReview.setContent(content);
        return this;
    }

    public EditorialReviewBuilder isLinkSuppressed(Boolean isLinkSuppressed) {
        editorialReview.setIsLinkSuppressed(isLinkSuppressed);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EditorialReview build() {
        return editorialReview;
    }
}