/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class HeaderBuilder {
    //the instance to build
    private Header header;

    /**
     * Default constructor to initialize the instance
     */
    public HeaderBuilder() {
        header = new Header();
    }

    public HeaderBuilder name(String name) {
        header.setName(name);
        return this;
    }

    public HeaderBuilder value(String value) {
        header.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Header build() {
        return header;
    }
}