/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class HTTPHeadersBuilder {
    //the instance to build
    private HTTPHeaders hTTPHeaders;

    /**
     * Default constructor to initialize the instance
     */
    public HTTPHeadersBuilder() {
        hTTPHeaders = new HTTPHeaders();
    }

    public HTTPHeadersBuilder header(List<Header> header) {
        hTTPHeaders.setHeader(header);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public HTTPHeaders build() {
        return hTTPHeaders;
    }
}