/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum IdTypeEnum {
    ASIN, //TODO: Write general description for this element
    UPC, //TODO: Write general description for this element
    SKU, //TODO: Write general description for this element
    EAN, //TODO: Write general description for this element
    ISBN; //TODO: Write general description for this element

    private static TreeMap<String, IdTypeEnum> valueMap = new TreeMap<String, IdTypeEnum>();
    private String value;

    static {
        ASIN.value = "ASIN";
        UPC.value = "UPC";
        SKU.value = "SKU";
        EAN.value = "EAN";
        ISBN.value = "ISBN";

        valueMap.put("ASIN", ASIN);
        valueMap.put("UPC", UPC);
        valueMap.put("SKU", SKU);
        valueMap.put("EAN", EAN);
        valueMap.put("ISBN", ISBN);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static IdTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of IdTypeEnum values to list of string values
     * @param toConvert The list of IdTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<IdTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (IdTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 