/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ImageBuilder {
    //the instance to build
    private Image image;

    /**
     * Default constructor to initialize the instance
     */
    public ImageBuilder() {
        image = new Image();
    }

    public ImageBuilder uRL(String uRL) {
        image.setURL(uRL);
        return this;
    }

    public ImageBuilder height(DecimalWithUnits height) {
        image.setHeight(height);
        return this;
    }

    public ImageBuilder width(DecimalWithUnits width) {
        image.setWidth(width);
        return this;
    }

    public ImageBuilder isVerified(String isVerified) {
        image.setIsVerified(isVerified);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Image build() {
        return image;
    }
}