/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ImageSetsBuilder {
    //the instance to build
    private ImageSets imageSets;

    /**
     * Default constructor to initialize the instance
     */
    public ImageSetsBuilder() {
        imageSets = new ImageSets();
    }

    public ImageSetsBuilder imageSet(List<ImageSet> imageSet) {
        imageSets.setImageSet(imageSet);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ImageSets build() {
        return imageSets;
    }
}