/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ImageSetBuilder {
    //the instance to build
    private ImageSet imageSet;

    /**
     * Default constructor to initialize the instance
     */
    public ImageSetBuilder() {
        imageSet = new ImageSet();
    }

    public ImageSetBuilder category(String category) {
        imageSet.setCategory(category);
        return this;
    }

    public ImageSetBuilder swatchImage(Image swatchImage) {
        imageSet.setSwatchImage(swatchImage);
        return this;
    }

    public ImageSetBuilder smallImage(Image smallImage) {
        imageSet.setSmallImage(smallImage);
        return this;
    }

    public ImageSetBuilder thumbnailImage(Image thumbnailImage) {
        imageSet.setThumbnailImage(thumbnailImage);
        return this;
    }

    public ImageSetBuilder tinyImage(Image tinyImage) {
        imageSet.setTinyImage(tinyImage);
        return this;
    }

    public ImageSetBuilder mediumImage(Image mediumImage) {
        imageSet.setMediumImage(mediumImage);
        return this;
    }

    public ImageSetBuilder largeImage(Image largeImage) {
        imageSet.setLargeImage(largeImage);
        return this;
    }

    public ImageSetBuilder hiResImage(Image hiResImage) {
        imageSet.setHiResImage(hiResImage);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ImageSet build() {
        return imageSet;
    }
}