/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemLookupBuilder {
    //the instance to build
    private ItemLookup itemLookup;

    /**
     * Default constructor to initialize the instance
     */
    public ItemLookupBuilder() {
        itemLookup = new ItemLookup();
    }

    public ItemLookupBuilder marketplaceDomain(String marketplaceDomain) {
        itemLookup.setMarketplaceDomain(marketplaceDomain);
        return this;
    }

    public ItemLookupBuilder aWSAccessKeyId(String aWSAccessKeyId) {
        itemLookup.setAWSAccessKeyId(aWSAccessKeyId);
        return this;
    }

    public ItemLookupBuilder associateTag(String associateTag) {
        itemLookup.setAssociateTag(associateTag);
        return this;
    }

    public ItemLookupBuilder validate(String validate) {
        itemLookup.setValidate(validate);
        return this;
    }

    public ItemLookupBuilder xMLEscaping(String xMLEscaping) {
        itemLookup.setXMLEscaping(xMLEscaping);
        return this;
    }

    public ItemLookupBuilder shared(ItemLookupRequest shared) {
        itemLookup.setShared(shared);
        return this;
    }

    public ItemLookupBuilder request(List<ItemLookupRequest> request) {
        itemLookup.setRequest(request);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemLookup build() {
        return itemLookup;
    }
}