/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemLookupRequestBuilder {
    //the instance to build
    private ItemLookupRequest itemLookupRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ItemLookupRequestBuilder() {
        itemLookupRequest = new ItemLookupRequest();
    }

    public ItemLookupRequestBuilder condition(ConditionEnum condition) {
        itemLookupRequest.setCondition(condition);
        return this;
    }

    public ItemLookupRequestBuilder idType(IdTypeEnum idType) {
        itemLookupRequest.setIdType(idType);
        return this;
    }

    public ItemLookupRequestBuilder merchantId(String merchantId) {
        itemLookupRequest.setMerchantId(merchantId);
        return this;
    }

    public ItemLookupRequestBuilder itemId(List<String> itemId) {
        itemLookupRequest.setItemId(itemId);
        return this;
    }

    public ItemLookupRequestBuilder responseGroup(List<String> responseGroup) {
        itemLookupRequest.setResponseGroup(responseGroup);
        return this;
    }

    public ItemLookupRequestBuilder searchIndex(String searchIndex) {
        itemLookupRequest.setSearchIndex(searchIndex);
        return this;
    }

    public ItemLookupRequestBuilder variationPage(Object variationPage) {
        itemLookupRequest.setVariationPage(variationPage);
        return this;
    }

    public ItemLookupRequestBuilder relatedItemPage(Object relatedItemPage) {
        itemLookupRequest.setRelatedItemPage(relatedItemPage);
        return this;
    }

    public ItemLookupRequestBuilder relationshipType(List<String> relationshipType) {
        itemLookupRequest.setRelationshipType(relationshipType);
        return this;
    }

    public ItemLookupRequestBuilder includeReviewsSummary(String includeReviewsSummary) {
        itemLookupRequest.setIncludeReviewsSummary(includeReviewsSummary);
        return this;
    }

    public ItemLookupRequestBuilder truncateReviewsAt(Integer truncateReviewsAt) {
        itemLookupRequest.setTruncateReviewsAt(truncateReviewsAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemLookupRequest build() {
        return itemLookupRequest;
    }
}