/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemSearchRequestBuilder {
    //the instance to build
    private ItemSearchRequest itemSearchRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ItemSearchRequestBuilder() {
        itemSearchRequest = new ItemSearchRequest();
    }

    public ItemSearchRequestBuilder actor(String actor) {
        itemSearchRequest.setActor(actor);
        return this;
    }

    public ItemSearchRequestBuilder artist(String artist) {
        itemSearchRequest.setArtist(artist);
        return this;
    }

    public ItemSearchRequestBuilder availability(AvailabilityEnum availability) {
        itemSearchRequest.setAvailability(availability);
        return this;
    }

    public ItemSearchRequestBuilder audienceRating(List<AudienceRatingEnum> audienceRating) {
        itemSearchRequest.setAudienceRating(audienceRating);
        return this;
    }

    public ItemSearchRequestBuilder author(String author) {
        itemSearchRequest.setAuthor(author);
        return this;
    }

    public ItemSearchRequestBuilder brand(String brand) {
        itemSearchRequest.setBrand(brand);
        return this;
    }

    public ItemSearchRequestBuilder browseNode(String browseNode) {
        itemSearchRequest.setBrowseNode(browseNode);
        return this;
    }

    public ItemSearchRequestBuilder composer(String composer) {
        itemSearchRequest.setComposer(composer);
        return this;
    }

    public ItemSearchRequestBuilder condition(ConditionEnum condition) {
        itemSearchRequest.setCondition(condition);
        return this;
    }

    public ItemSearchRequestBuilder conductor(String conductor) {
        itemSearchRequest.setConductor(conductor);
        return this;
    }

    public ItemSearchRequestBuilder director(String director) {
        itemSearchRequest.setDirector(director);
        return this;
    }

    public ItemSearchRequestBuilder itemPage(Integer itemPage) {
        itemSearchRequest.setItemPage(itemPage);
        return this;
    }

    public ItemSearchRequestBuilder keywords(String keywords) {
        itemSearchRequest.setKeywords(keywords);
        return this;
    }

    public ItemSearchRequestBuilder manufacturer(String manufacturer) {
        itemSearchRequest.setManufacturer(manufacturer);
        return this;
    }

    public ItemSearchRequestBuilder maximumPrice(Integer maximumPrice) {
        itemSearchRequest.setMaximumPrice(maximumPrice);
        return this;
    }

    public ItemSearchRequestBuilder merchantId(String merchantId) {
        itemSearchRequest.setMerchantId(merchantId);
        return this;
    }

    public ItemSearchRequestBuilder minimumPrice(Integer minimumPrice) {
        itemSearchRequest.setMinimumPrice(minimumPrice);
        return this;
    }

    public ItemSearchRequestBuilder minPercentageOff(Integer minPercentageOff) {
        itemSearchRequest.setMinPercentageOff(minPercentageOff);
        return this;
    }

    public ItemSearchRequestBuilder musicLabel(String musicLabel) {
        itemSearchRequest.setMusicLabel(musicLabel);
        return this;
    }

    public ItemSearchRequestBuilder orchestra(String orchestra) {
        itemSearchRequest.setOrchestra(orchestra);
        return this;
    }

    public ItemSearchRequestBuilder power(String power) {
        itemSearchRequest.setPower(power);
        return this;
    }

    public ItemSearchRequestBuilder publisher(String publisher) {
        itemSearchRequest.setPublisher(publisher);
        return this;
    }

    public ItemSearchRequestBuilder relatedItemPage(Object relatedItemPage) {
        itemSearchRequest.setRelatedItemPage(relatedItemPage);
        return this;
    }

    public ItemSearchRequestBuilder relationshipType(List<String> relationshipType) {
        itemSearchRequest.setRelationshipType(relationshipType);
        return this;
    }

    public ItemSearchRequestBuilder responseGroup(List<String> responseGroup) {
        itemSearchRequest.setResponseGroup(responseGroup);
        return this;
    }

    public ItemSearchRequestBuilder searchIndex(String searchIndex) {
        itemSearchRequest.setSearchIndex(searchIndex);
        return this;
    }

    public ItemSearchRequestBuilder sort(String sort) {
        itemSearchRequest.setSort(sort);
        return this;
    }

    public ItemSearchRequestBuilder title(String title) {
        itemSearchRequest.setTitle(title);
        return this;
    }

    public ItemSearchRequestBuilder releaseDate(String releaseDate) {
        itemSearchRequest.setReleaseDate(releaseDate);
        return this;
    }

    public ItemSearchRequestBuilder includeReviewsSummary(String includeReviewsSummary) {
        itemSearchRequest.setIncludeReviewsSummary(includeReviewsSummary);
        return this;
    }

    public ItemSearchRequestBuilder truncateReviewsAt(Integer truncateReviewsAt) {
        itemSearchRequest.setTruncateReviewsAt(truncateReviewsAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemSearchRequest build() {
        return itemSearchRequest;
    }
}