/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Item23Builder {
    //the instance to build
    private Item23 item23;

    /**
     * Default constructor to initialize the instance
     */
    public Item23Builder() {
        item23 = new Item23();
    }

    public Item23Builder aSIN(String aSIN) {
        item23.setASIN(aSIN);
        return this;
    }

    public Item23Builder offerListingId(String offerListingId) {
        item23.setOfferListingId(offerListingId);
        return this;
    }

    public Item23Builder quantity(Integer quantity) {
        item23.setQuantity(quantity);
        return this;
    }

    public Item23Builder associateTag(String associateTag) {
        item23.setAssociateTag(associateTag);
        return this;
    }

    public Item23Builder listItemId(String listItemId) {
        item23.setListItemId(listItemId);
        return this;
    }

    public Item23Builder metaData(List<MetaData> metaData) {
        item23.setMetaData(metaData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item23 build() {
        return item23;
    }
}