/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemSearchRequestMsgBuilder {
    //the instance to build
    private ItemSearchRequestMsg itemSearchRequestMsg;

    /**
     * Default constructor to initialize the instance
     */
    public ItemSearchRequestMsgBuilder() {
        itemSearchRequestMsg = new ItemSearchRequestMsg();
    }

    public ItemSearchRequestMsgBuilder body(ItemSearch body) {
        itemSearchRequestMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemSearchRequestMsg build() {
        return itemSearchRequestMsg;
    }
}