/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemsBuilder {
    //the instance to build
    private Items items;

    /**
     * Default constructor to initialize the instance
     */
    public ItemsBuilder() {
        items = new Items();
    }

    public ItemsBuilder item(List<Item> item) {
        items.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Items build() {
        return items;
    }
}