/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemBuilder {
    //the instance to build
    private Item item;

    /**
     * Default constructor to initialize the instance
     */
    public ItemBuilder() {
        item = new Item();
    }

    public ItemBuilder aSIN(String aSIN) {
        item.setASIN(aSIN);
        return this;
    }

    public ItemBuilder offerListingId(String offerListingId) {
        item.setOfferListingId(offerListingId);
        return this;
    }

    public ItemBuilder quantity(Integer quantity) {
        item.setQuantity(quantity);
        return this;
    }

    public ItemBuilder associateTag(String associateTag) {
        item.setAssociateTag(associateTag);
        return this;
    }

    public ItemBuilder listItemId(String listItemId) {
        item.setListItemId(listItemId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item build() {
        return item;
    }
}