/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemDimensionsBuilder {
    //the instance to build
    private ItemDimensions itemDimensions;

    /**
     * Default constructor to initialize the instance
     */
    public ItemDimensionsBuilder() {
        itemDimensions = new ItemDimensions();
    }

    public ItemDimensionsBuilder height(DecimalWithUnits height) {
        itemDimensions.setHeight(height);
        return this;
    }

    public ItemDimensionsBuilder length(DecimalWithUnits length) {
        itemDimensions.setLength(length);
        return this;
    }

    public ItemDimensionsBuilder weight(DecimalWithUnits weight) {
        itemDimensions.setWeight(weight);
        return this;
    }

    public ItemDimensionsBuilder width(DecimalWithUnits width) {
        itemDimensions.setWidth(width);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemDimensions build() {
        return itemDimensions;
    }
}