/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Items35Builder {
    //the instance to build
    private Items35 items35;

    /**
     * Default constructor to initialize the instance
     */
    public Items35Builder() {
        items35 = new Items35();
    }

    public Items35Builder item(List<Item34> item) {
        items35.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Items35 build() {
        return items35;
    }
}