/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Item133Builder {
    //the instance to build
    private Item133 item133;

    /**
     * Default constructor to initialize the instance
     */
    public Item133Builder() {
        item133 = new Item133();
    }

    public Item133Builder aSIN(String aSIN) {
        item133.setASIN(aSIN);
        return this;
    }

    public Item133Builder parentASIN(String parentASIN) {
        item133.setParentASIN(parentASIN);
        return this;
    }

    public Item133Builder errors(Errors errors) {
        item133.setErrors(errors);
        return this;
    }

    public Item133Builder detailPageURL(String detailPageURL) {
        item133.setDetailPageURL(detailPageURL);
        return this;
    }

    public Item133Builder itemLinks(ItemLinks itemLinks) {
        item133.setItemLinks(itemLinks);
        return this;
    }

    public Item133Builder salesRank(String salesRank) {
        item133.setSalesRank(salesRank);
        return this;
    }

    public Item133Builder smallImage(Image smallImage) {
        item133.setSmallImage(smallImage);
        return this;
    }

    public Item133Builder mediumImage(Image mediumImage) {
        item133.setMediumImage(mediumImage);
        return this;
    }

    public Item133Builder largeImage(Image largeImage) {
        item133.setLargeImage(largeImage);
        return this;
    }

    public Item133Builder imageSets(List<ImageSets> imageSets) {
        item133.setImageSets(imageSets);
        return this;
    }

    public Item133Builder itemAttributes(ItemAttributes itemAttributes) {
        item133.setItemAttributes(itemAttributes);
        return this;
    }

    public Item133Builder variationAttributes(VariationAttributes variationAttributes) {
        item133.setVariationAttributes(variationAttributes);
        return this;
    }

    public Item133Builder relatedItems(List<RelatedItems> relatedItems) {
        item133.setRelatedItems(relatedItems);
        return this;
    }

    public Item133Builder collections(Collections collections) {
        item133.setCollections(collections);
        return this;
    }

    public Item133Builder subjects(Subjects subjects) {
        item133.setSubjects(subjects);
        return this;
    }

    public Item133Builder offerSummary(OfferSummary offerSummary) {
        item133.setOfferSummary(offerSummary);
        return this;
    }

    public Item133Builder offers(Offers offers) {
        item133.setOffers(offers);
        return this;
    }

    public Item133Builder rentalOffers(RentalOffers rentalOffers) {
        item133.setRentalOffers(rentalOffers);
        return this;
    }

    public Item133Builder variationSummary(VariationSummary variationSummary) {
        item133.setVariationSummary(variationSummary);
        return this;
    }

    public Item133Builder variations(Variations variations) {
        item133.setVariations(variations);
        return this;
    }

    public Item133Builder customerReviews(CustomerReviews customerReviews) {
        item133.setCustomerReviews(customerReviews);
        return this;
    }

    public Item133Builder editorialReviews(EditorialReviews editorialReviews) {
        item133.setEditorialReviews(editorialReviews);
        return this;
    }

    public Item133Builder similarProducts(SimilarProducts similarProducts) {
        item133.setSimilarProducts(similarProducts);
        return this;
    }

    public Item133Builder accessories(Accessories accessories) {
        item133.setAccessories(accessories);
        return this;
    }

    public Item133Builder tracks(Tracks tracks) {
        item133.setTracks(tracks);
        return this;
    }

    public Item133Builder browseNodes(BrowseNodes browseNodes) {
        item133.setBrowseNodes(browseNodes);
        return this;
    }

    public Item133Builder alternateVersions(AlternateVersions alternateVersions) {
        item133.setAlternateVersions(alternateVersions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item133 build() {
        return item133;
    }
}