/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Items134Builder {
    //the instance to build
    private Items134 items134;

    /**
     * Default constructor to initialize the instance
     */
    public Items134Builder() {
        items134 = new Items134();
    }

    public Items134Builder request(Request request) {
        items134.setRequest(request);
        return this;
    }

    public Items134Builder correctedQuery(CorrectedQuery correctedQuery) {
        items134.setCorrectedQuery(correctedQuery);
        return this;
    }

    public Items134Builder qid(String qid) {
        items134.setQid(qid);
        return this;
    }

    public Items134Builder engineQuery(String engineQuery) {
        items134.setEngineQuery(engineQuery);
        return this;
    }

    public Items134Builder totalResults(Integer totalResults) {
        items134.setTotalResults(totalResults);
        return this;
    }

    public Items134Builder totalPages(Integer totalPages) {
        items134.setTotalPages(totalPages);
        return this;
    }

    public Items134Builder moreSearchResultsUrl(String moreSearchResultsUrl) {
        items134.setMoreSearchResultsUrl(moreSearchResultsUrl);
        return this;
    }

    public Items134Builder searchResultsMap(SearchResultsMap searchResultsMap) {
        items134.setSearchResultsMap(searchResultsMap);
        return this;
    }

    public Items134Builder item(List<Item133> item) {
        items134.setItem(item);
        return this;
    }

    public Items134Builder searchBinSets(SearchBinSets searchBinSets) {
        items134.setSearchBinSets(searchBinSets);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Items134 build() {
        return items134;
    }
}