/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemLinksBuilder {
    //the instance to build
    private ItemLinks itemLinks;

    /**
     * Default constructor to initialize the instance
     */
    public ItemLinksBuilder() {
        itemLinks = new ItemLinks();
    }

    public ItemLinksBuilder itemLink(List<ItemLink> itemLink) {
        itemLinks.setItemLink(itemLink);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemLinks build() {
        return itemLinks;
    }
}