/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemLookupResponseBuilder {
    //the instance to build
    private ItemLookupResponse itemLookupResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ItemLookupResponseBuilder() {
        itemLookupResponse = new ItemLookupResponse();
    }

    public ItemLookupResponseBuilder operationRequest(OperationRequest operationRequest) {
        itemLookupResponse.setOperationRequest(operationRequest);
        return this;
    }

    public ItemLookupResponseBuilder items(List<Items134> items) {
        itemLookupResponse.setItems(items);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemLookupResponse build() {
        return itemLookupResponse;
    }
}