/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemLookupRequestMsgBuilder {
    //the instance to build
    private ItemLookupRequestMsg itemLookupRequestMsg;

    /**
     * Default constructor to initialize the instance
     */
    public ItemLookupRequestMsgBuilder() {
        itemLookupRequestMsg = new ItemLookupRequestMsg();
    }

    public ItemLookupRequestMsgBuilder body(ItemLookup body) {
        itemLookupRequestMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemLookupRequestMsg build() {
        return itemLookupRequestMsg;
    }
}