/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Item34 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5162016993991738603L;
    private ActionEnum action;
    private String cartItemId;
    private Integer quantity;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Action")
    public ActionEnum getAction ( ) { 
        return this.action;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Action")
    public void setAction (ActionEnum value) { 
        this.action = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CartItemId")
    public String getCartItemId ( ) { 
        return this.cartItemId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CartItemId")
    public void setCartItemId (String value) { 
        this.cartItemId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Quantity")
    public Integer getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Quantity")
    public void setQuantity (Integer value) { 
        this.quantity = value;
    }
 
}
 