/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemSearchResponseBuilder {
    //the instance to build
    private ItemSearchResponse itemSearchResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ItemSearchResponseBuilder() {
        itemSearchResponse = new ItemSearchResponse();
    }

    public ItemSearchResponseBuilder operationRequest(OperationRequest operationRequest) {
        itemSearchResponse.setOperationRequest(operationRequest);
        return this;
    }

    public ItemSearchResponseBuilder items(List<Items134> items) {
        itemSearchResponse.setItems(items);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemSearchResponse build() {
        return itemSearchResponse;
    }
}