/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemSearchResponseMsgBuilder {
    //the instance to build
    private ItemSearchResponseMsg itemSearchResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public ItemSearchResponseMsgBuilder() {
        itemSearchResponseMsg = new ItemSearchResponseMsg();
    }

    public ItemSearchResponseMsgBuilder body(ItemSearchResponse body) {
        itemSearchResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemSearchResponseMsg build() {
        return itemSearchResponseMsg;
    }
}