/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ItemLinks 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4903211265500999960L;
    private List<ItemLink> itemLink;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ItemLink")
    public List<ItemLink> getItemLink ( ) { 
        return this.itemLink;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ItemLink")
    public void setItemLink (List<ItemLink> value) { 
        this.itemLink = value;
    }
 
}
 