/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class ItemLinkBuilder {
    //the instance to build
    private ItemLink itemLink;

    /**
     * Default constructor to initialize the instance
     */
    public ItemLinkBuilder() {
        itemLink = new ItemLink();
    }

    public ItemLinkBuilder description(String description) {
        itemLink.setDescription(description);
        return this;
    }

    public ItemLinkBuilder uRL(String uRL) {
        itemLink.setURL(uRL);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemLink build() {
        return itemLink;
    }
}