/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class LanguagesBuilder {
    //the instance to build
    private Languages languages;

    /**
     * Default constructor to initialize the instance
     */
    public LanguagesBuilder() {
        languages = new Languages();
    }

    public LanguagesBuilder language(List<Language> language) {
        languages.setLanguage(language);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Languages build() {
        return languages;
    }
}