/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Languages 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5578015778715933146L;
    private List<Language> language;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Language")
    public List<Language> getLanguage ( ) { 
        return this.language;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Language")
    public void setLanguage (List<Language> value) { 
        this.language = value;
    }
 
}
 