/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class LoyaltyPointsBuilder {
    //the instance to build
    private LoyaltyPoints loyaltyPoints;

    /**
     * Default constructor to initialize the instance
     */
    public LoyaltyPointsBuilder() {
        loyaltyPoints = new LoyaltyPoints();
    }

    public LoyaltyPointsBuilder points(Integer points) {
        loyaltyPoints.setPoints(points);
        return this;
    }

    public LoyaltyPointsBuilder typicalRedemptionValue(Price typicalRedemptionValue) {
        loyaltyPoints.setTypicalRedemptionValue(typicalRedemptionValue);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LoyaltyPoints build() {
        return loyaltyPoints;
    }
}