/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class MCollectionBuilder {
    //the instance to build
    private MCollection mCollection;

    /**
     * Default constructor to initialize the instance
     */
    public MCollectionBuilder() {
        mCollection = new MCollection();
    }

    public MCollectionBuilder collectionSummary(CollectionSummary collectionSummary) {
        mCollection.setCollectionSummary(collectionSummary);
        return this;
    }

    public MCollectionBuilder collectionParent(CollectionParent collectionParent) {
        mCollection.setCollectionParent(collectionParent);
        return this;
    }

    public MCollectionBuilder collectionItem(List<CollectionItem> collectionItem) {
        mCollection.setCollectionItem(collectionItem);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MCollection build() {
        return mCollection;
    }
}