/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class MerchantBuilder {
    //the instance to build
    private Merchant merchant;

    /**
     * Default constructor to initialize the instance
     */
    public MerchantBuilder() {
        merchant = new Merchant();
    }

    public MerchantBuilder name(String name) {
        merchant.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Merchant build() {
        return merchant;
    }
}