/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class MetaData164Builder {
    //the instance to build
    private MetaData164 metaData164;

    /**
     * Default constructor to initialize the instance
     */
    public MetaData164Builder() {
        metaData164 = new MetaData164();
    }

    public MetaData164Builder keyValuePair(List<KeyValuePair> keyValuePair) {
        metaData164.setKeyValuePair(keyValuePair);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MetaData164 build() {
        return metaData164;
    }
}