/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class MetaDataBuilder {
    //the instance to build
    private MetaData metaData;

    /**
     * Default constructor to initialize the instance
     */
    public MetaDataBuilder() {
        metaData = new MetaData();
    }

    public MetaDataBuilder key(String key) {
        metaData.setKey(key);
        return this;
    }

    public MetaDataBuilder value(String value) {
        metaData.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MetaData build() {
        return metaData;
    }
}