/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class NewReleasesBuilder {
    //the instance to build
    private NewReleases newReleases;

    /**
     * Default constructor to initialize the instance
     */
    public NewReleasesBuilder() {
        newReleases = new NewReleases();
    }

    public NewReleasesBuilder newRelease(List<NewRelease> newRelease) {
        newReleases.setNewRelease(newRelease);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NewReleases build() {
        return newReleases;
    }
}