/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class NewReleaseBuilder {
    //the instance to build
    private NewRelease newRelease;

    /**
     * Default constructor to initialize the instance
     */
    public NewReleaseBuilder() {
        newRelease = new NewRelease();
    }

    public NewReleaseBuilder aSIN(String aSIN) {
        newRelease.setASIN(aSIN);
        return this;
    }

    public NewReleaseBuilder title(String title) {
        newRelease.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NewRelease build() {
        return newRelease;
    }
}