/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class NonNegativeIntegerWithUnitsBuilder {
    //the instance to build
    private NonNegativeIntegerWithUnits nonNegativeIntegerWithUnits;

    /**
     * Default constructor to initialize the instance
     */
    public NonNegativeIntegerWithUnitsBuilder() {
        nonNegativeIntegerWithUnits = new NonNegativeIntegerWithUnits();
    }

    public NonNegativeIntegerWithUnitsBuilder units(String units) {
        nonNegativeIntegerWithUnits.setUnits(units);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NonNegativeIntegerWithUnits build() {
        return nonNegativeIntegerWithUnits;
    }
}