/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class OfferSummaryBuilder {
    //the instance to build
    private OfferSummary offerSummary;

    /**
     * Default constructor to initialize the instance
     */
    public OfferSummaryBuilder() {
        offerSummary = new OfferSummary();
    }

    public OfferSummaryBuilder lowestNewPrice(Price lowestNewPrice) {
        offerSummary.setLowestNewPrice(lowestNewPrice);
        return this;
    }

    public OfferSummaryBuilder lowestUsedPrice(Price lowestUsedPrice) {
        offerSummary.setLowestUsedPrice(lowestUsedPrice);
        return this;
    }

    public OfferSummaryBuilder lowestCollectiblePrice(Price lowestCollectiblePrice) {
        offerSummary.setLowestCollectiblePrice(lowestCollectiblePrice);
        return this;
    }

    public OfferSummaryBuilder lowestRefurbishedPrice(Price lowestRefurbishedPrice) {
        offerSummary.setLowestRefurbishedPrice(lowestRefurbishedPrice);
        return this;
    }

    public OfferSummaryBuilder totalNew(String totalNew) {
        offerSummary.setTotalNew(totalNew);
        return this;
    }

    public OfferSummaryBuilder totalUsed(String totalUsed) {
        offerSummary.setTotalUsed(totalUsed);
        return this;
    }

    public OfferSummaryBuilder totalCollectible(String totalCollectible) {
        offerSummary.setTotalCollectible(totalCollectible);
        return this;
    }

    public OfferSummaryBuilder totalRefurbished(String totalRefurbished) {
        offerSummary.setTotalRefurbished(totalRefurbished);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OfferSummary build() {
        return offerSummary;
    }
}