/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class OfferBuilder {
    //the instance to build
    private Offer offer;

    /**
     * Default constructor to initialize the instance
     */
    public OfferBuilder() {
        offer = new Offer();
    }

    public OfferBuilder merchant(Merchant merchant) {
        offer.setMerchant(merchant);
        return this;
    }

    public OfferBuilder offerAttributes(OfferAttributes offerAttributes) {
        offer.setOfferAttributes(offerAttributes);
        return this;
    }

    public OfferBuilder offerListing(List<OfferListing> offerListing) {
        offer.setOfferListing(offerListing);
        return this;
    }

    public OfferBuilder loyaltyPoints(LoyaltyPoints loyaltyPoints) {
        offer.setLoyaltyPoints(loyaltyPoints);
        return this;
    }

    public OfferBuilder promotions(Promotions promotions) {
        offer.setPromotions(promotions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Offer build() {
        return offer;
    }
}