/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Offer 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5694750015018645068L;
    private Merchant merchant;
    private OfferAttributes offerAttributes;
    private List<OfferListing> offerListing;
    private LoyaltyPoints loyaltyPoints;
    private Promotions promotions;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Merchant")
    public Merchant getMerchant ( ) { 
        return this.merchant;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Merchant")
    public void setMerchant (Merchant value) { 
        this.merchant = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("OfferAttributes")
    public OfferAttributes getOfferAttributes ( ) { 
        return this.offerAttributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("OfferAttributes")
    public void setOfferAttributes (OfferAttributes value) { 
        this.offerAttributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("OfferListing")
    public List<OfferListing> getOfferListing ( ) { 
        return this.offerListing;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("OfferListing")
    public void setOfferListing (List<OfferListing> value) { 
        this.offerListing = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("LoyaltyPoints")
    public LoyaltyPoints getLoyaltyPoints ( ) { 
        return this.loyaltyPoints;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("LoyaltyPoints")
    public void setLoyaltyPoints (LoyaltyPoints value) { 
        this.loyaltyPoints = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Promotions")
    public Promotions getPromotions ( ) { 
        return this.promotions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Promotions")
    public void setPromotions (Promotions value) { 
        this.promotions = value;
    }
 
}
 