/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class OffersBuilder {
    //the instance to build
    private Offers offers;

    /**
     * Default constructor to initialize the instance
     */
    public OffersBuilder() {
        offers = new Offers();
    }

    public OffersBuilder totalOffers(Integer totalOffers) {
        offers.setTotalOffers(totalOffers);
        return this;
    }

    public OffersBuilder totalOfferPages(Integer totalOfferPages) {
        offers.setTotalOfferPages(totalOfferPages);
        return this;
    }

    public OffersBuilder moreOffersUrl(String moreOffersUrl) {
        offers.setMoreOffersUrl(moreOffersUrl);
        return this;
    }

    public OffersBuilder offer(List<Offer> offer) {
        offers.setOffer(offer);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Offers build() {
        return offers;
    }
}