/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class OfferListingBuilder {
    //the instance to build
    private OfferListing offerListing;

    /**
     * Default constructor to initialize the instance
     */
    public OfferListingBuilder() {
        offerListing = new OfferListing();
    }

    public OfferListingBuilder offerListingId(String offerListingId) {
        offerListing.setOfferListingId(offerListingId);
        return this;
    }

    public OfferListingBuilder pricePerUnit(String pricePerUnit) {
        offerListing.setPricePerUnit(pricePerUnit);
        return this;
    }

    public OfferListingBuilder price(Price price) {
        offerListing.setPrice(price);
        return this;
    }

    public OfferListingBuilder salePrice(Price salePrice) {
        offerListing.setSalePrice(salePrice);
        return this;
    }

    public OfferListingBuilder amountSaved(Price amountSaved) {
        offerListing.setAmountSaved(amountSaved);
        return this;
    }

    public OfferListingBuilder percentageSaved(Integer percentageSaved) {
        offerListing.setPercentageSaved(percentageSaved);
        return this;
    }

    public OfferListingBuilder availability(String availability) {
        offerListing.setAvailability(availability);
        return this;
    }

    public OfferListingBuilder availabilityAttributes(AvailabilityAttributes availabilityAttributes) {
        offerListing.setAvailabilityAttributes(availabilityAttributes);
        return this;
    }

    public OfferListingBuilder isEligibleForSuperSaverShipping(Boolean isEligibleForSuperSaverShipping) {
        offerListing.setIsEligibleForSuperSaverShipping(isEligibleForSuperSaverShipping);
        return this;
    }

    public OfferListingBuilder isEligibleForPrimeFreeDigitalVideo(Boolean isEligibleForPrimeFreeDigitalVideo) {
        offerListing.setIsEligibleForPrimeFreeDigitalVideo(isEligibleForPrimeFreeDigitalVideo);
        return this;
    }

    public OfferListingBuilder isEligibleForPrime(Boolean isEligibleForPrime) {
        offerListing.setIsEligibleForPrime(isEligibleForPrime);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OfferListing build() {
        return offerListing;
    }
}