/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class OperationRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5172977648142575929L;
    private HTTPHeaders hTTPHeaders;
    private String requestId;
    private Arguments arguments;
    private Errors errors;
    private Double requestProcessingTime;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("HTTPHeaders")
    public HTTPHeaders getHTTPHeaders ( ) { 
        return this.hTTPHeaders;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("HTTPHeaders")
    public void setHTTPHeaders (HTTPHeaders value) { 
        this.hTTPHeaders = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("RequestId")
    public String getRequestId ( ) { 
        return this.requestId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("RequestId")
    public void setRequestId (String value) { 
        this.requestId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Arguments")
    public Arguments getArguments ( ) { 
        return this.arguments;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Arguments")
    public void setArguments (Arguments value) { 
        this.arguments = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Errors")
    public Errors getErrors ( ) { 
        return this.errors;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Errors")
    public void setErrors (Errors value) { 
        this.errors = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("RequestProcessingTime")
    public Double getRequestProcessingTime ( ) { 
        return this.requestProcessingTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("RequestProcessingTime")
    public void setRequestProcessingTime (Double value) { 
        this.requestProcessingTime = value;
    }
 
}
 