/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class OperationRequestBuilder {
    //the instance to build
    private OperationRequest operationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public OperationRequestBuilder() {
        operationRequest = new OperationRequest();
    }

    public OperationRequestBuilder hTTPHeaders(HTTPHeaders hTTPHeaders) {
        operationRequest.setHTTPHeaders(hTTPHeaders);
        return this;
    }

    public OperationRequestBuilder requestId(String requestId) {
        operationRequest.setRequestId(requestId);
        return this;
    }

    public OperationRequestBuilder arguments(Arguments arguments) {
        operationRequest.setArguments(arguments);
        return this;
    }

    public OperationRequestBuilder errors(Errors errors) {
        operationRequest.setErrors(errors);
        return this;
    }

    public OperationRequestBuilder requestProcessingTime(Double requestProcessingTime) {
        operationRequest.setRequestProcessingTime(requestProcessingTime);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OperationRequest build() {
        return operationRequest;
    }
}