/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class OtherCategoriesSimilarProductsBuilder {
    //the instance to build
    private OtherCategoriesSimilarProducts otherCategoriesSimilarProducts;

    /**
     * Default constructor to initialize the instance
     */
    public OtherCategoriesSimilarProductsBuilder() {
        otherCategoriesSimilarProducts = new OtherCategoriesSimilarProducts();
    }

    public OtherCategoriesSimilarProductsBuilder otherCategoriesSimilarProduct(List<OtherCategoriesSimilarProduct> otherCategoriesSimilarProduct) {
        otherCategoriesSimilarProducts.setOtherCategoriesSimilarProduct(otherCategoriesSimilarProduct);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OtherCategoriesSimilarProducts build() {
        return otherCategoriesSimilarProducts;
    }
}