/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class OtherCategoriesSimilarProductBuilder {
    //the instance to build
    private OtherCategoriesSimilarProduct otherCategoriesSimilarProduct;

    /**
     * Default constructor to initialize the instance
     */
    public OtherCategoriesSimilarProductBuilder() {
        otherCategoriesSimilarProduct = new OtherCategoriesSimilarProduct();
    }

    public OtherCategoriesSimilarProductBuilder aSIN(String aSIN) {
        otherCategoriesSimilarProduct.setASIN(aSIN);
        return this;
    }

    public OtherCategoriesSimilarProductBuilder title(String title) {
        otherCategoriesSimilarProduct.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OtherCategoriesSimilarProduct build() {
        return otherCategoriesSimilarProduct;
    }
}