/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class PriceBuilder {
    //the instance to build
    private Price price;

    /**
     * Default constructor to initialize the instance
     */
    public PriceBuilder() {
        price = new Price();
    }

    public PriceBuilder formattedPrice(String formattedPrice) {
        price.setFormattedPrice(formattedPrice);
        return this;
    }

    public PriceBuilder amount(Integer amount) {
        price.setAmount(amount);
        return this;
    }

    public PriceBuilder currencyCode(String currencyCode) {
        price.setCurrencyCode(currencyCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Price build() {
        return price;
    }
}