/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class PromotionBuilder {
    //the instance to build
    private Promotion promotion;

    /**
     * Default constructor to initialize the instance
     */
    public PromotionBuilder() {
        promotion = new Promotion();
    }

    public PromotionBuilder summary(Summary summary) {
        promotion.setSummary(summary);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Promotion build() {
        return promotion;
    }
}