/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class PromotionsBuilder {
    //the instance to build
    private Promotions promotions;

    /**
     * Default constructor to initialize the instance
     */
    public PromotionsBuilder() {
        promotions = new Promotions();
    }

    public PromotionsBuilder promotion(List<Promotion> promotion) {
        promotions.setPromotion(promotion);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Promotions build() {
        return promotions;
    }
}