/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class PropertyBuilder {
    //the instance to build
    private Property property;

    /**
     * Default constructor to initialize the instance
     */
    public PropertyBuilder() {
        property = new Property();
    }

    public PropertyBuilder name(String name) {
        property.setName(name);
        return this;
    }

    public PropertyBuilder value(String value) {
        property.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Property build() {
        return property;
    }
}