/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Properties 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4730918369606887597L;
    private List<Property> property;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Property")
    public List<Property> getProperty ( ) { 
        return this.property;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Property")
    public void setProperty (List<Property> value) { 
        this.property = value;
    }
 
}
 