/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class PropertiesBuilder {
    //the instance to build
    private Properties properties;

    /**
     * Default constructor to initialize the instance
     */
    public PropertiesBuilder() {
        properties = new Properties();
    }

    public PropertiesBuilder property(List<Property> property) {
        properties.setProperty(property);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Properties build() {
        return properties;
    }
}