/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RelatedItem264 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5198056447691735318L;
    private Item253 item;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Item")
    public Item253 getItem ( ) { 
        return this.item;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Item")
    public void setItem (Item253 value) { 
        this.item = value;
    }
 
}
 