/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class RelatedItems265Builder {
    //the instance to build
    private RelatedItems265 relatedItems265;

    /**
     * Default constructor to initialize the instance
     */
    public RelatedItems265Builder() {
        relatedItems265 = new RelatedItems265();
    }

    public RelatedItems265Builder relationship(RelationshipEnum relationship) {
        relatedItems265.setRelationship(relationship);
        return this;
    }

    public RelatedItems265Builder relationshipType(String relationshipType) {
        relatedItems265.setRelationshipType(relationshipType);
        return this;
    }

    public RelatedItems265Builder relatedItemCount(Integer relatedItemCount) {
        relatedItems265.setRelatedItemCount(relatedItemCount);
        return this;
    }

    public RelatedItems265Builder relatedItemPageCount(Integer relatedItemPageCount) {
        relatedItems265.setRelatedItemPageCount(relatedItemPageCount);
        return this;
    }

    public RelatedItems265Builder relatedItemPage(Integer relatedItemPage) {
        relatedItems265.setRelatedItemPage(relatedItemPage);
        return this;
    }

    public RelatedItems265Builder relatedItem(List<RelatedItem264> relatedItem) {
        relatedItems265.setRelatedItem(relatedItem);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RelatedItems265 build() {
        return relatedItems265;
    }
}