/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class RelatedItemsBuilder {
    //the instance to build
    private RelatedItems relatedItems;

    /**
     * Default constructor to initialize the instance
     */
    public RelatedItemsBuilder() {
        relatedItems = new RelatedItems();
    }

    public RelatedItemsBuilder relationship(RelationshipEnum relationship) {
        relatedItems.setRelationship(relationship);
        return this;
    }

    public RelatedItemsBuilder relationshipType(String relationshipType) {
        relatedItems.setRelationshipType(relationshipType);
        return this;
    }

    public RelatedItemsBuilder relatedItemCount(Integer relatedItemCount) {
        relatedItems.setRelatedItemCount(relatedItemCount);
        return this;
    }

    public RelatedItemsBuilder relatedItemPageCount(Integer relatedItemPageCount) {
        relatedItems.setRelatedItemPageCount(relatedItemPageCount);
        return this;
    }

    public RelatedItemsBuilder relatedItemPage(Integer relatedItemPage) {
        relatedItems.setRelatedItemPage(relatedItemPage);
        return this;
    }

    public RelatedItemsBuilder relatedItem(List<RelatedItem> relatedItem) {
        relatedItems.setRelatedItem(relatedItem);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RelatedItems build() {
        return relatedItems;
    }
}