/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class RelatedItemBuilder {
    //the instance to build
    private RelatedItem relatedItem;

    /**
     * Default constructor to initialize the instance
     */
    public RelatedItemBuilder() {
        relatedItem = new RelatedItem();
    }

    public RelatedItemBuilder item(Item item) {
        relatedItem.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RelatedItem build() {
        return relatedItem;
    }
}