/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum RelationshipEnum {
    PARENTS, //TODO: Write general description for this element
    CHILDREN; //TODO: Write general description for this element

    private static TreeMap<String, RelationshipEnum> valueMap = new TreeMap<String, RelationshipEnum>();
    private String value;

    static {
        PARENTS.value = "Parents";
        CHILDREN.value = "Children";

        valueMap.put("Parents", PARENTS);
        valueMap.put("Children", CHILDREN);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static RelationshipEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of RelationshipEnum values to list of string values
     * @param toConvert The list of RelationshipEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<RelationshipEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (RelationshipEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 