/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class RentalOffersBuilder {
    //the instance to build
    private RentalOffers rentalOffers;

    /**
     * Default constructor to initialize the instance
     */
    public RentalOffersBuilder() {
        rentalOffers = new RentalOffers();
    }

    public RentalOffersBuilder rentalOffer(List<RentalOffer> rentalOffer) {
        rentalOffers.setRentalOffer(rentalOffer);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RentalOffers build() {
        return rentalOffers;
    }
}