/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class RentalListingBuilder {
    //the instance to build
    private RentalListing rentalListing;

    /**
     * Default constructor to initialize the instance
     */
    public RentalListingBuilder() {
        rentalListing = new RentalListing();
    }

    public RentalListingBuilder price(Price price) {
        rentalListing.setPrice(price);
        return this;
    }

    public RentalListingBuilder period(NonNegativeIntegerWithUnits period) {
        rentalListing.setPeriod(period);
        return this;
    }

    public RentalListingBuilder isFulfilledByAmazon(Boolean isFulfilledByAmazon) {
        rentalListing.setIsFulfilledByAmazon(isFulfilledByAmazon);
        return this;
    }

    public RentalListingBuilder disclaimer(String disclaimer) {
        rentalListing.setDisclaimer(disclaimer);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RentalListing build() {
        return rentalListing;
    }
}