/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RentalOffer 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4614945776072952746L;
    private Merchant merchant;
    private List<RentalListing> rentalListing;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Merchant")
    public Merchant getMerchant ( ) { 
        return this.merchant;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Merchant")
    public void setMerchant (Merchant value) { 
        this.merchant = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("RentalListing")
    public List<RentalListing> getRentalListing ( ) { 
        return this.rentalListing;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("RentalListing")
    public void setRentalListing (List<RentalListing> value) { 
        this.rentalListing = value;
    }
 
}
 