/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class RentalOfferBuilder {
    //the instance to build
    private RentalOffer rentalOffer;

    /**
     * Default constructor to initialize the instance
     */
    public RentalOfferBuilder() {
        rentalOffer = new RentalOffer();
    }

    public RentalOfferBuilder merchant(Merchant merchant) {
        rentalOffer.setMerchant(merchant);
        return this;
    }

    public RentalOfferBuilder rentalListing(List<RentalListing> rentalListing) {
        rentalOffer.setRentalListing(rentalListing);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RentalOffer build() {
        return rentalOffer;
    }
}