/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Request162Builder {
    //the instance to build
    private Request162 request162;

    /**
     * Default constructor to initialize the instance
     */
    public Request162Builder() {
        request162 = new Request162();
    }

    public Request162Builder isValid(String isValid) {
        request162.setIsValid(isValid);
        return this;
    }

    public Request162Builder browseNodeLookupRequest(BrowseNodeLookupRequest browseNodeLookupRequest) {
        request162.setBrowseNodeLookupRequest(browseNodeLookupRequest);
        return this;
    }

    public Request162Builder itemSearchRequest(ItemSearchRequest itemSearchRequest) {
        request162.setItemSearchRequest(itemSearchRequest);
        return this;
    }

    public Request162Builder itemLookupRequest(ItemLookupRequest itemLookupRequest) {
        request162.setItemLookupRequest(itemLookupRequest);
        return this;
    }

    public Request162Builder similarityLookupRequest(SimilarityLookupRequest similarityLookupRequest) {
        request162.setSimilarityLookupRequest(similarityLookupRequest);
        return this;
    }

    public Request162Builder cartGetRequest(CartGetRequest cartGetRequest) {
        request162.setCartGetRequest(cartGetRequest);
        return this;
    }

    public Request162Builder cartAddRequest(CartAddRequest cartAddRequest) {
        request162.setCartAddRequest(cartAddRequest);
        return this;
    }

    public Request162Builder cartCreateRequest(CartCreateRequest cartCreateRequest) {
        request162.setCartCreateRequest(cartCreateRequest);
        return this;
    }

    public Request162Builder cartModifyRequest(CartModifyRequest cartModifyRequest) {
        request162.setCartModifyRequest(cartModifyRequest);
        return this;
    }

    public Request162Builder cartClearRequest(CartClearRequest cartClearRequest) {
        request162.setCartClearRequest(cartClearRequest);
        return this;
    }

    public Request162Builder errors(Errors errors) {
        request162.setErrors(errors);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Request162 build() {
        return request162;
    }
}