/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SavedForLaterItemsBuilder {
    //the instance to build
    private SavedForLaterItems savedForLaterItems;

    /**
     * Default constructor to initialize the instance
     */
    public SavedForLaterItemsBuilder() {
        savedForLaterItems = new SavedForLaterItems();
    }

    public SavedForLaterItemsBuilder savedForLaterItem(List<CartItem> savedForLaterItem) {
        savedForLaterItems.setSavedForLaterItem(savedForLaterItem);
        return this;
    }

    public SavedForLaterItemsBuilder subTotal(Price subTotal) {
        savedForLaterItems.setSubTotal(subTotal);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SavedForLaterItems build() {
        return savedForLaterItems;
    }
}