/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SearchBinSetBuilder {
    //the instance to build
    private SearchBinSet searchBinSet;

    /**
     * Default constructor to initialize the instance
     */
    public SearchBinSetBuilder() {
        searchBinSet = new SearchBinSet();
    }

    public SearchBinSetBuilder narrowBy(String narrowBy) {
        searchBinSet.setNarrowBy(narrowBy);
        return this;
    }

    public SearchBinSetBuilder bin(List<Bin> bin) {
        searchBinSet.setBin(bin);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchBinSet build() {
        return searchBinSet;
    }
}