/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SearchBinSetsBuilder {
    //the instance to build
    private SearchBinSets searchBinSets;

    /**
     * Default constructor to initialize the instance
     */
    public SearchBinSetsBuilder() {
        searchBinSets = new SearchBinSets();
    }

    public SearchBinSetsBuilder searchBinSet(List<SearchBinSet> searchBinSet) {
        searchBinSets.setSearchBinSet(searchBinSet);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchBinSets build() {
        return searchBinSets;
    }
}