/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SearchBinSets 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5643711040838327176L;
    private List<SearchBinSet> searchBinSet;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SearchBinSet")
    public List<SearchBinSet> getSearchBinSet ( ) { 
        return this.searchBinSet;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SearchBinSet")
    public void setSearchBinSet (List<SearchBinSet> value) { 
        this.searchBinSet = value;
    }
 
}
 