/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SearchIndex 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5750370262146016777L;
    private String indexName;
    private int relevanceRank;
    private List<String> aSIN;
    private Integer results;
    private Integer pages;
    private CorrectedQuery correctedQuery;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("IndexName")
    public String getIndexName ( ) { 
        return this.indexName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("IndexName")
    public void setIndexName (String value) { 
        this.indexName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("RelevanceRank")
    public int getRelevanceRank ( ) { 
        return this.relevanceRank;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("RelevanceRank")
    public void setRelevanceRank (int value) { 
        this.relevanceRank = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ASIN")
    public List<String> getASIN ( ) { 
        return this.aSIN;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ASIN")
    public void setASIN (List<String> value) { 
        this.aSIN = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Results")
    public Integer getResults ( ) { 
        return this.results;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Results")
    public void setResults (Integer value) { 
        this.results = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Pages")
    public Integer getPages ( ) { 
        return this.pages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Pages")
    public void setPages (Integer value) { 
        this.pages = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CorrectedQuery")
    public CorrectedQuery getCorrectedQuery ( ) { 
        return this.correctedQuery;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CorrectedQuery")
    public void setCorrectedQuery (CorrectedQuery value) { 
        this.correctedQuery = value;
    }
 
}
 