/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarViewedProductsBuilder {
    //the instance to build
    private SimilarViewedProducts similarViewedProducts;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarViewedProductsBuilder() {
        similarViewedProducts = new SimilarViewedProducts();
    }

    public SimilarViewedProductsBuilder similarViewedProduct(List<SimilarViewedProduct> similarViewedProduct) {
        similarViewedProducts.setSimilarViewedProduct(similarViewedProduct);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarViewedProducts build() {
        return similarViewedProducts;
    }
}