/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarityLookupRequestMsgBuilder {
    //the instance to build
    private SimilarityLookupRequestMsg similarityLookupRequestMsg;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarityLookupRequestMsgBuilder() {
        similarityLookupRequestMsg = new SimilarityLookupRequestMsg();
    }

    public SimilarityLookupRequestMsgBuilder body(SimilarityLookup body) {
        similarityLookupRequestMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarityLookupRequestMsg build() {
        return similarityLookupRequestMsg;
    }
}