/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarProductBuilder {
    //the instance to build
    private SimilarProduct similarProduct;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarProductBuilder() {
        similarProduct = new SimilarProduct();
    }

    public SimilarProductBuilder aSIN(String aSIN) {
        similarProduct.setASIN(aSIN);
        return this;
    }

    public SimilarProductBuilder title(String title) {
        similarProduct.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarProduct build() {
        return similarProduct;
    }
}