/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum SimilarityTypeEnum {
    INTERSECTION, //TODO: Write general description for this element
    RANDOM; //TODO: Write general description for this element

    private static TreeMap<String, SimilarityTypeEnum> valueMap = new TreeMap<String, SimilarityTypeEnum>();
    private String value;

    static {
        INTERSECTION.value = "Intersection";
        RANDOM.value = "Random";

        valueMap.put("Intersection", INTERSECTION);
        valueMap.put("Random", RANDOM);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static SimilarityTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of SimilarityTypeEnum values to list of string values
     * @param toConvert The list of SimilarityTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<SimilarityTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (SimilarityTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 