/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarProductsBuilder {
    //the instance to build
    private SimilarProducts similarProducts;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarProductsBuilder() {
        similarProducts = new SimilarProducts();
    }

    public SimilarProductsBuilder similarProduct(List<SimilarProduct> similarProduct) {
        similarProducts.setSimilarProduct(similarProduct);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarProducts build() {
        return similarProducts;
    }
}