/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarityLookupResponseMsgBuilder {
    //the instance to build
    private SimilarityLookupResponseMsg similarityLookupResponseMsg;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarityLookupResponseMsgBuilder() {
        similarityLookupResponseMsg = new SimilarityLookupResponseMsg();
    }

    public SimilarityLookupResponseMsgBuilder body(SimilarityLookupResponse body) {
        similarityLookupResponseMsg.setBody(body);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarityLookupResponseMsg build() {
        return similarityLookupResponseMsg;
    }
}