/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarityLookupRequestBuilder {
    //the instance to build
    private SimilarityLookupRequest similarityLookupRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarityLookupRequestBuilder() {
        similarityLookupRequest = new SimilarityLookupRequest();
    }

    public SimilarityLookupRequestBuilder condition(ConditionEnum condition) {
        similarityLookupRequest.setCondition(condition);
        return this;
    }

    public SimilarityLookupRequestBuilder itemId(List<String> itemId) {
        similarityLookupRequest.setItemId(itemId);
        return this;
    }

    public SimilarityLookupRequestBuilder merchantId(String merchantId) {
        similarityLookupRequest.setMerchantId(merchantId);
        return this;
    }

    public SimilarityLookupRequestBuilder responseGroup(List<String> responseGroup) {
        similarityLookupRequest.setResponseGroup(responseGroup);
        return this;
    }

    public SimilarityLookupRequestBuilder similarityType(SimilarityTypeEnum similarityType) {
        similarityLookupRequest.setSimilarityType(similarityType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarityLookupRequest build() {
        return similarityLookupRequest;
    }
}