/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarityLookupResponseBuilder {
    //the instance to build
    private SimilarityLookupResponse similarityLookupResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarityLookupResponseBuilder() {
        similarityLookupResponse = new SimilarityLookupResponse();
    }

    public SimilarityLookupResponseBuilder operationRequest(OperationRequest operationRequest) {
        similarityLookupResponse.setOperationRequest(operationRequest);
        return this;
    }

    public SimilarityLookupResponseBuilder items(List<Items134> items) {
        similarityLookupResponse.setItems(items);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarityLookupResponse build() {
        return similarityLookupResponse;
    }
}