/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarViewedProductBuilder {
    //the instance to build
    private SimilarViewedProduct similarViewedProduct;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarViewedProductBuilder() {
        similarViewedProduct = new SimilarViewedProduct();
    }

    public SimilarViewedProductBuilder aSIN(String aSIN) {
        similarViewedProduct.setASIN(aSIN);
        return this;
    }

    public SimilarViewedProductBuilder title(String title) {
        similarViewedProduct.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarViewedProduct build() {
        return similarViewedProduct;
    }
}