/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SimilarityLookupBuilder {
    //the instance to build
    private SimilarityLookup similarityLookup;

    /**
     * Default constructor to initialize the instance
     */
    public SimilarityLookupBuilder() {
        similarityLookup = new SimilarityLookup();
    }

    public SimilarityLookupBuilder marketplaceDomain(String marketplaceDomain) {
        similarityLookup.setMarketplaceDomain(marketplaceDomain);
        return this;
    }

    public SimilarityLookupBuilder aWSAccessKeyId(String aWSAccessKeyId) {
        similarityLookup.setAWSAccessKeyId(aWSAccessKeyId);
        return this;
    }

    public SimilarityLookupBuilder associateTag(String associateTag) {
        similarityLookup.setAssociateTag(associateTag);
        return this;
    }

    public SimilarityLookupBuilder validate(String validate) {
        similarityLookup.setValidate(validate);
        return this;
    }

    public SimilarityLookupBuilder xMLEscaping(String xMLEscaping) {
        similarityLookup.setXMLEscaping(xMLEscaping);
        return this;
    }

    public SimilarityLookupBuilder shared(SimilarityLookupRequest shared) {
        similarityLookup.setShared(shared);
        return this;
    }

    public SimilarityLookupBuilder request(List<SimilarityLookupRequest> request) {
        similarityLookup.setRequest(request);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SimilarityLookup build() {
        return similarityLookup;
    }
}