/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class StringWithUnitsBuilder {
    //the instance to build
    private StringWithUnits stringWithUnits;

    /**
     * Default constructor to initialize the instance
     */
    public StringWithUnitsBuilder() {
        stringWithUnits = new StringWithUnits();
    }

    public StringWithUnitsBuilder units(String units) {
        stringWithUnits.setUnits(units);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StringWithUnits build() {
        return stringWithUnits;
    }
}