/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SubjectsBuilder {
    //the instance to build
    private Subjects subjects;

    /**
     * Default constructor to initialize the instance
     */
    public SubjectsBuilder() {
        subjects = new Subjects();
    }

    public SubjectsBuilder subject(List<String> subject) {
        subjects.setSubject(subject);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Subjects build() {
        return subjects;
    }
}