/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class SummaryBuilder {
    //the instance to build
    private Summary summary;

    /**
     * Default constructor to initialize the instance
     */
    public SummaryBuilder() {
        summary = new Summary();
    }

    public SummaryBuilder promotionId(String promotionId) {
        summary.setPromotionId(promotionId);
        return this;
    }

    public SummaryBuilder message(String message) {
        summary.setMessage(message);
        return this;
    }

    public SummaryBuilder category(String category) {
        summary.setCategory(category);
        return this;
    }

    public SummaryBuilder startDate(String startDate) {
        summary.setStartDate(startDate);
        return this;
    }

    public SummaryBuilder endDate(String endDate) {
        summary.setEndDate(endDate);
        return this;
    }

    public SummaryBuilder eligibilityRequirementDescription(String eligibilityRequirementDescription) {
        summary.setEligibilityRequirementDescription(eligibilityRequirementDescription);
        return this;
    }

    public SummaryBuilder benefitDescription(String benefitDescription) {
        summary.setBenefitDescription(benefitDescription);
        return this;
    }

    public SummaryBuilder termsAndConditions(String termsAndConditions) {
        summary.setTermsAndConditions(termsAndConditions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Summary build() {
        return summary;
    }
}