/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class TopItemSetBuilder {
    //the instance to build
    private TopItemSet topItemSet;

    /**
     * Default constructor to initialize the instance
     */
    public TopItemSetBuilder() {
        topItemSet = new TopItemSet();
    }

    public TopItemSetBuilder topItem(List<TopItem> topItem) {
        topItemSet.setTopItem(topItem);
        return this;
    }

    public TopItemSetBuilder type(String type) {
        topItemSet.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TopItemSet build() {
        return topItemSet;
    }
}