/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TopItemSet 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5696852118492038254L;
    private List<TopItem> topItem;
    private String type;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("TopItem")
    public List<TopItem> getTopItem ( ) { 
        return this.topItem;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("TopItem")
    public void setTopItem (List<TopItem> value) { 
        this.topItem = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 