/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class TopSellerBuilder {
    //the instance to build
    private TopSeller topSeller;

    /**
     * Default constructor to initialize the instance
     */
    public TopSellerBuilder() {
        topSeller = new TopSeller();
    }

    public TopSellerBuilder aSIN(String aSIN) {
        topSeller.setASIN(aSIN);
        return this;
    }

    public TopSellerBuilder title(String title) {
        topSeller.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TopSeller build() {
        return topSeller;
    }
}