/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class TrackBuilder {
    //the instance to build
    private Track track;

    /**
     * Default constructor to initialize the instance
     */
    public TrackBuilder() {
        track = new Track();
    }

    public TrackBuilder number(int number) {
        track.setNumber(number);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Track build() {
        return track;
    }
}