/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class TracksBuilder {
    //the instance to build
    private Tracks tracks;

    /**
     * Default constructor to initialize the instance
     */
    public TracksBuilder() {
        tracks = new Tracks();
    }

    public TracksBuilder disc(List<Disc> disc) {
        tracks.setDisc(disc);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Tracks build() {
        return tracks;
    }
}