/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Track 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5117112582464720263L;
    private int number;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Number")
    public int getNumber ( ) { 
        return this.number;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Number")
    public void setNumber (int value) { 
        this.number = value;
    }
 
}
 