/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class UPCListBuilder {
    //the instance to build
    private UPCList uPCList;

    /**
     * Default constructor to initialize the instance
     */
    public UPCListBuilder() {
        uPCList = new UPCList();
    }

    public UPCListBuilder uPCListElement(List<String> uPCListElement) {
        uPCList.setUPCListElement(uPCListElement);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UPCList build() {
        return uPCList;
    }
}