/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class UPCList 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5192555933104496124L;
    private List<String> uPCListElement;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("UPCListElement")
    public List<String> getUPCListElement ( ) { 
        return this.uPCListElement;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("UPCListElement")
    public void setUPCListElement (List<String> value) { 
        this.uPCListElement = value;
    }
 
}
 