/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class VariationSummary 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4712551070946537981L;
    private Price lowestPrice;
    private Price highestPrice;
    private Price lowestSalePrice;
    private Price highestSalePrice;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("LowestPrice")
    public Price getLowestPrice ( ) { 
        return this.lowestPrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("LowestPrice")
    public void setLowestPrice (Price value) { 
        this.lowestPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("HighestPrice")
    public Price getHighestPrice ( ) { 
        return this.highestPrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("HighestPrice")
    public void setHighestPrice (Price value) { 
        this.highestPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("LowestSalePrice")
    public Price getLowestSalePrice ( ) { 
        return this.lowestSalePrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("LowestSalePrice")
    public void setLowestSalePrice (Price value) { 
        this.lowestSalePrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("HighestSalePrice")
    public Price getHighestSalePrice ( ) { 
        return this.highestSalePrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("HighestSalePrice")
    public void setHighestSalePrice (Price value) { 
        this.highestSalePrice = value;
    }
 
}
 