/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class VariationSummaryBuilder {
    //the instance to build
    private VariationSummary variationSummary;

    /**
     * Default constructor to initialize the instance
     */
    public VariationSummaryBuilder() {
        variationSummary = new VariationSummary();
    }

    public VariationSummaryBuilder lowestPrice(Price lowestPrice) {
        variationSummary.setLowestPrice(lowestPrice);
        return this;
    }

    public VariationSummaryBuilder highestPrice(Price highestPrice) {
        variationSummary.setHighestPrice(highestPrice);
        return this;
    }

    public VariationSummaryBuilder lowestSalePrice(Price lowestSalePrice) {
        variationSummary.setLowestSalePrice(lowestSalePrice);
        return this;
    }

    public VariationSummaryBuilder highestSalePrice(Price highestSalePrice) {
        variationSummary.setHighestSalePrice(highestSalePrice);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VariationSummary build() {
        return variationSummary;
    }
}