/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class VariationDimensionsBuilder {
    //the instance to build
    private VariationDimensions variationDimensions;

    /**
     * Default constructor to initialize the instance
     */
    public VariationDimensionsBuilder() {
        variationDimensions = new VariationDimensions();
    }

    public VariationDimensionsBuilder variationDimension(List<String> variationDimension) {
        variationDimensions.setVariationDimension(variationDimension);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VariationDimensions build() {
        return variationDimensions;
    }
}