/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class VariationAttributesBuilder {
    //the instance to build
    private VariationAttributes variationAttributes;

    /**
     * Default constructor to initialize the instance
     */
    public VariationAttributesBuilder() {
        variationAttributes = new VariationAttributes();
    }

    public VariationAttributesBuilder variationAttribute(List<VariationAttribute> variationAttribute) {
        variationAttributes.setVariationAttribute(variationAttribute);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VariationAttributes build() {
        return variationAttributes;
    }
}