/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class VariationsBuilder {
    //the instance to build
    private Variations variations;

    /**
     * Default constructor to initialize the instance
     */
    public VariationsBuilder() {
        variations = new Variations();
    }

    public VariationsBuilder totalVariations(Integer totalVariations) {
        variations.setTotalVariations(totalVariations);
        return this;
    }

    public VariationsBuilder totalVariationPages(Integer totalVariationPages) {
        variations.setTotalVariationPages(totalVariationPages);
        return this;
    }

    public VariationsBuilder variationDimensions(VariationDimensions variationDimensions) {
        variations.setVariationDimensions(variationDimensions);
        return this;
    }

    public VariationsBuilder item(List<Item> item) {
        variations.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Variations build() {
        return variations;
    }
}