/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;

public class Variations267Builder {
    //the instance to build
    private Variations267 variations267;

    /**
     * Default constructor to initialize the instance
     */
    public Variations267Builder() {
        variations267 = new Variations267();
    }

    public Variations267Builder totalVariations(Integer totalVariations) {
        variations267.setTotalVariations(totalVariations);
        return this;
    }

    public Variations267Builder totalVariationPages(Integer totalVariationPages) {
        variations267.setTotalVariationPages(totalVariationPages);
        return this;
    }

    public Variations267Builder variationDimensions(VariationDimensions variationDimensions) {
        variations267.setVariationDimensions(variationDimensions);
        return this;
    }

    public Variations267Builder item(List<Item253> item) {
        variations267.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Variations267 build() {
        return variations267;
    }
}