/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices;

import com.amazon.webservices.controllers.*;
import com.amazon.webservices.http.client.HttpClient;

public class AWSECommerceServiceClient {
    /**
     * Singleton access to AWSECommerceServiceBinding controller
     * @return	Returns the AWSECommerceServiceBindingController instance 
     */
    public AWSECommerceServiceBindingController getAWSECommerceServiceBinding() {
        return AWSECommerceServiceBindingController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public AWSECommerceServiceClient() {
    }

}