/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum Servers {
    AWSECOMMERCESERVICEPORT, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTCA, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTCN, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTDE, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTES, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTFR, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTIN, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTIT, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTJP, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTUK, //TODO: Write general description for this element
    AWSECOMMERCESERVICEPORTUS; //TODO: Write general description for this element

    private static TreeMap<String, Servers> valueMap = new TreeMap<String, Servers>();
    private String value;

    static {
        AWSECOMMERCESERVICEPORT.value = "AWSECommerceServicePort";
        AWSECOMMERCESERVICEPORTCA.value = "AWSECommerceServicePortCA";
        AWSECOMMERCESERVICEPORTCN.value = "AWSECommerceServicePortCN";
        AWSECOMMERCESERVICEPORTDE.value = "AWSECommerceServicePortDE";
        AWSECOMMERCESERVICEPORTES.value = "AWSECommerceServicePortES";
        AWSECOMMERCESERVICEPORTFR.value = "AWSECommerceServicePortFR";
        AWSECOMMERCESERVICEPORTIN.value = "AWSECommerceServicePortIN";
        AWSECOMMERCESERVICEPORTIT.value = "AWSECommerceServicePortIT";
        AWSECOMMERCESERVICEPORTJP.value = "AWSECommerceServicePortJP";
        AWSECOMMERCESERVICEPORTUK.value = "AWSECommerceServicePortUK";
        AWSECOMMERCESERVICEPORTUS.value = "AWSECommerceServicePortUS";

        valueMap.put("AWSECommerceServicePort", AWSECOMMERCESERVICEPORT);
        valueMap.put("AWSECommerceServicePortCA", AWSECOMMERCESERVICEPORTCA);
        valueMap.put("AWSECommerceServicePortCN", AWSECOMMERCESERVICEPORTCN);
        valueMap.put("AWSECommerceServicePortDE", AWSECOMMERCESERVICEPORTDE);
        valueMap.put("AWSECommerceServicePortES", AWSECOMMERCESERVICEPORTES);
        valueMap.put("AWSECommerceServicePortFR", AWSECOMMERCESERVICEPORTFR);
        valueMap.put("AWSECommerceServicePortIN", AWSECOMMERCESERVICEPORTIN);
        valueMap.put("AWSECommerceServicePortIT", AWSECOMMERCESERVICEPORTIT);
        valueMap.put("AWSECommerceServicePortJP", AWSECOMMERCESERVICEPORTJP);
        valueMap.put("AWSECommerceServicePortUK", AWSECOMMERCESERVICEPORTUK);
        valueMap.put("AWSECommerceServicePortUS", AWSECOMMERCESERVICEPORTUS);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Servers fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Servers values to list of string values
     * @param toConvert The list of Servers values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<Servers> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (Servers enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 